### ISSUE TITLE
When presence is updated, a leave event happens even though untrack() is never called

### ISSUE THREAD

**Issue by JOsacky** [supabase/realtime#1030]
# Bug report

## Describe the bug

Calling track() with both the swift and kotlin library cause join and leave to be called at the same time on the server. This causes the presence to never be tracked because the leave event happens every time. I'm reporting this bug because it seems to happen on both kotlin and swift libraries. 

## To Reproduce
kotlin repro: 
```
            checkNotNull(supabaseRealtimeChannel).track(
                ignoreUnknownKeysJson.encodeToJsonElement(fleetPresence).jsonObject
            )
 ```
 
 swift repro: 
 ```
                     try await channel?.track(
                        presence
                    )
 ```

## Expected behavior

I expect only join to be broadcast when track() is called

## Screenshots
Screen shot to show the leave and join event happen at the same server time, which looks like the server is triggering an immediate leave event

<img width="1041" alt="image" src="https://github.com/supabase/realtime/assets/1144450/9e90f1c1-6e8a-4224-9865-5bbe3e3f68ed">

## System information

- OS: android, iOS
- Version of supabase-kotlin: 2.4.2
- Version of supabase-swift: 2.11.0

**Comment by JOsacky** [comment]
I figured out that whenever the presence is updated, a leave event and a join event happen at the same time. This is expected behavior even though it is a bit confusing. You should process the leave events first and then the join events so that your presence cache is accurate after an update. There was a bug in the kotlin library where join events were processed first which caused presence to always be empty for updates. I submitted a PR to fix, but make sure this is happening in whatever client you use realtime in. PR to fix: https://github.com/supabase-community/supabase-kt/pull/607

I'd still like to pose the question, should clients receive "leaves" events for a user that is still present but is just updating their presence data?

**Comment by w3b6x9** [comment]
@JOsacky I don't think this is an issue with the Realtime server. We have logic that if something has already been tracked then we simply update the Presence payload: https://github.com/supabase/realtime/blob/2f64285718d659d594cc3cc1abcab616ff8dff26/lib/realtime_web/channels/realtime_channel/presence_handler.ex#L72

Also, looking at `realtime-js` we just have `track`: https://github.com/supabase/realtime-js/blob/b3eafe820f61afdb4c663fa600c4f209757ba8b4/src/RealtimeChannel.ts#L196

Then when it's sent to Realtime server it'll determine if payload is being tracked for the first time and if not update the payload.

I think it has more to do with how Swift and Kotlin libs have implemented aspects of Realtime Presence. @grdsdev just making sure you're aware for the Swift lib.

**Comment by JOsacky** [comment]
@w3b6x9 its not an issue with the swift library. Each update for presence contains join and leave events. I was noting that it happens with swift and kotlin libraries to show it seems to be agnostic of the platform that sends the event.

Is the server sending leave and join events for update events by design? Sending both can cause issues and confusion for clients. It caused a bug in the kotlin library and it was also confusing to see this happen in the realtime inspector as seeing both can cause someone to think presence was tracked and then untracked at the same time. 

Something that would've saved me a lot of time is documentation of this unexpected behavior

**Comment by JOsacky** [comment]
> https://github.com/supabase/realtime/blob/2f64285718d659d594cc3cc1abcab616ff8dff26/lib/realtime_web/channels/realtime_channel/presence_handler.ex#L72
> 

Thank you for sending the implementation over. After looking at it I see we are calling `Phoenix.Presence` APIs so I'm not sure there is much we can do to change that behavior, maybe this thread can serve as documentation that updates contain both joins and leaves? Unless there is a better spot for it

Appreciate your help and response :)

**Comment by netgfx** [comment]
I'm seeing the same thing on javascript as well, everytime track is called I get the events of join and leave to fire

**Comment by JOsacky** [comment]
> I'm seeing the same thing on javascript as well, everytime track is called I get the events of join and leave to fire

This is expected behavior and if you process the leaves before the joins then you'll have the correct cache

**Comment by netgfx** [comment]
That might be slightly difficult without manually adding some delay because they seem to be arriving at the same time
![image](https://github.com/user-attachments/assets/48dec35a-95a6-4350-8669-3500ac6937ca)

**Comment by JOsacky** [comment]
> That might be slightly difficult without manually adding some delay because they seem to be arriving at the same time !

No delay is necessary, just iterate through the leaves first then the joins. Here is how the kotlin library processes events, you should do something similar on your platform

```
inline fun <reified Data> RealtimeChannel.presenceDataFlow(): Flow<List<Data>> {
    val cache = AtomicMutableMap<String, Data>()
    return presenceChangeFlow().map {
        // order matters here, leaves events must happen first for updates to work properly
        it.leaves.forEach { (key, _) ->
            cache.remove(key)
        }
        it.joins.forEach { (key, presence) ->
            cache[key] = presence.stateAs<Data>(supabaseClient.realtime.serializer)
        }
        cache.values.toList()
    }
}
```

**Comment by netgfx** [comment]
Hm not sure if we can do something similar in JS because the join and leave are captured in event listeners (according to the official documentation) and these are async, so my guess is that the js SDK is capturing these on the same message but then goes on and transmits the events individually
