### ISSUE TITLE
Local Docker supabase_realtime_next hitting "relation \"todos\" does not exist", postgres_updates aren't broadcasted.

### ISSUE THREAD

**Issue by m-tse** [supabase/realtime#1074]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Local Docker supabase_realtime_next hitting "relation \"todos\" does not exist", postgres_updates aren't broadcasted.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow all the [quick start settings for postgres changes](https://supabase.com/docs/guides/realtime/postgres-changes), for a dev docker supabase instance
  - create a todos table
  - allow anonymous access
  - enable postgres replication
  - subscribe to schema changes
  ```
  import { createClient } from '@supabase/supabase-js'
  const client = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  );
  const channelA = client
    .channel('schema-db-changes')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
      },
      (payload) => console.log(payload),
    ).subscribe()
  ```
2. Issue a triggered update
```
insert into todos (task) values ('Change!');
```

## Expected behavior

I expect my clients to print the payload for the change, but that never happens.

When I look into the docker logs on the supabase_realtime_next docker container, I see the following error message whenever I trigger an update:
```
2024-06-12 15:41:35   postgres: %{
2024-06-12 15:41:35     code: :undefined_table,
2024-06-12 15:41:35     file: "parse_relation.c",
2024-06-12 15:41:35     internal_position: "161",
2024-06-12 15:41:35     internal_query: "execute walrus_rls_stmt",
2024-06-12 15:41:35     line: "1392",
2024-06-12 15:41:35     message: "relation \"todos\" does not exist",
2024-06-12 15:41:35     pg_code: "42P01",
2024-06-12 15:41:35     routine: "parserOpenTable",
2024-06-12 15:41:35     severity: "ERROR",
2024-06-12 15:41:35     unknown: "ERROR",
2024-06-12 15:41:35     where: "PL/pgSQL function realtime.apply_rls(jsonb,integer) line 267 at EXECUTE\nSQL function \"list_changes\" statement 1"
2024-06-12 15:41:35   },
```

This is strange, as I've configured the todos table exactly as specified.

## Screenshots

See todos_table, database_publication, and rls_policy screenshots to confirm my settings
<img width="1077" alt="todos_table" src="https://github.com/supabase/realtime/assets/1315979/7f3b99aa-853c-4106-823f-bb5d182b4d22">
<img width="906" alt="database_publication" src="https://github.com/supabase/realtime/assets/1315979/3424244b-ef7f-4423-929a-b6e584b10fa1">
<img width="666" alt="rls_policy" src="https://github.com/supabase/realtime/assets/1315979/7a28e96d-2ce7-4478-b843-22edd08fe6db">

## System information

- OS: macOS
- Version of supabase-js: 2.43.4
- Version of supabase cli: v1.176.4
- Version of supabase realtime: v2.28.32

## Additional context

NOTE: weirdly, if I kill my node client, and restart the supabase_realtime_next docker container, and trigger an update, then the error in docker doesn't appear anymore. And if I visit the realtime inspector, I see my triggered updates happening. But once I start my node client, and issue the subscribe() command, that puts supabase_realtime_next into a bad state, and updates won't happen anymore until I restart the docker container.

**Comment by m-tse** [comment]
In an attempt to get myself unblocked here, I created a new supabase online hosted project at wjoudjjhdadahiqkwvjd (instead of my local docker version of this), and I set everything up the same, and ended up getting the same error in the supabase realtime logs:

```
"[error_message: \"%Postgrex.Error{\\n  message: nil,\\n  postgres: %{\\n    code: :undefined_table,\\n    line: \\\"1392\\\",\\n    message: \\\"relation \\\\\\\"todos\\\\\\\" does not exist\\\",\\n    file: \\\"parse_relation.c\\\",\\n    unknown: \\\"ERROR\\\",\\n    where: \\\"PL/pgSQL function realtime.apply_rls(jsonb,integer) line 267 at EXECUTE\\\\nSQL function \\\\\\\"list_changes\\\\\\\" statement 1\\\",\\n    severity: \\\"ERROR\\\",\\n    pg_code: \\\"42P01\\\",\\n    internal_query: \\\"execute walrus_rls_stmt\\\",\\n    internal_position: \\\"161\\\",\\n    routine: \\\"parserOpenTable\\\"\\n  },\\n  connection_id: 3029,\\n  query: nil\\n}\", error_code: \"PoolingReplicationError\"]"
```

Though there seems to be a new component to the error, it says `PoolingReplicationError`.

So perhaps there's something wrong with my custom set of triggers that is causing this issue?

**Comment by m-tse** [comment]
I managed to get myself working here.

I think it had something to do with: the supabase boilerplate I'm using has us run `revoke all PRIVILEGES on database "postgres" from "anon"`. Which may have caused issues with supabase realtime being able to connect with the database.

I ran `GRANT CONNECT ON DATABASE "postgres" TO "anon";`, and that seems to have fixed my issue

**Comment by filipecabaco** [comment]
Hey @m-tse !

That fix makes sense due to the fact that we will use the role from the user to run the pooling query so what probably was happening was that the pooling query was executing with the anon role and that would hit that policy.

**Comment by m-tse** [comment]
Thanks for the reply!

Yeah unfortunately this had me run around in circles for a few days. Perhaps a more guiding error message, or some documentation about what kind of SQL policies are required for realtime to work, would have led me to the solution faster.

Though I understand if it's difficult to account for all situations (you guys certainly don't control what my boilerplate repo told me to do!).

**Comment by filipecabaco** [comment]
Yes, we really need to do a HUGE refactor in all our docs (README and Supabase website ones!) and that is our next big thing to ensure we can streamline a lot of this and improve both the Supabase usage of Realtime but also the self hosting usage of Realtime as that is currently really lacking at the moment...

Will take this as feedback and be sure to add a section regarding policy impact and requirements for Realtime usage 🙏
