### ISSUE TITLE
Performance Advisor foreign key index

### ISSUE THREAD

**Issue by jdgamble555** [supabase/realtime#1140]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The performance advisor indicates this:
```
Table _realtime.extensions has a foreign key extensions_tenant_external_id_fkey without a covering index. 
This can lead to suboptimal query performance.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Run any instance of supabase on the local machine.

## Expected behavior

The index would be automatically created by Supabase.

## Screenshots

![Unindexed foreign keys](https://github.com/user-attachments/assets/25ab5add-82b7-4e23-896d-9a8138562578)

## System information

- OS: [e.g. macOS, Windows]
- supabase - ^1.191.3

## Additional context

Should just be automatically created. Easy fix.

J

**Comment by filipecabaco** [comment]
PR was merged, closing the issue
