### ISSUE TITLE
Client-side example with a chart of routing time

### ISSUE THREAD

**Issue by abc3** [supabase/realtime#115]
# Feature request

## Is your feature request related to a problem? Please describe.

You can never have too many examples, especially about measurement. It would be helpful to see a client example that shows a simple time chart by getting updates from DB.

## Describe the solution you'd like

Insert N rows to DB, receive them, and show timestamps on the chart.

## Additional context

I've already done it, take a look at https://github.com/abc3/realtime/commit/003824a2928894e6e5ad8f7219329a44f1c46be8.  If everything ok, let me know, I will make PR.
<img width="574" alt="Screenshot" src="https://user-images.githubusercontent.com/1172600/107123177-c8ef8e00-68a4-11eb-88ad-4fc4e828a7a8.png">

**Comment by kiwicopple** [comment]
wow, this is awesome 🔥 

> You can never have too many examples

😂  agreed

@w3b6x9 if you're happy with this let's merge it

**Comment by w3b6x9** [comment]
Closing this issue b/c #118 has been merged.
