### ISSUE TITLE
Unable to subscribe to postgres with filters

### ISSUE THREAD

**Issue by MaximeLemolt** [supabase/realtime#1161]
# Bug report

I have a problem when I try to listen to UPDATE changes with Supabase realtime.

Realtime logs error message :
> "UnableToSubscribeToPostgres: {:error,\n \"Unable to subscribe to changes with given parameters. An exception happened so please check your connect parameters: [event: UPDATE, filter: id=eq.6100895b-7991-4f12-bed5-41708fa06176, schema: public, table: Player]. Exception: ERROR P0001 (raise_exception) invalid column for filter id\"}"

My code :
```
const channel = realtime.channel(`player-updates`);
channel.on(
  "postgres_changes",
  {
    event: "UPDATE",
    schema: "public",
    table: "Player",
    filter: `id=eq.${player.id}`,
  },
  (payload) => {
    console.log(payload);
  }
);

channel.subscribe(async (status) => {
  if (status === "SUBSCRIBED") {
    console.log("Ready to receive updates");
  }
});
```

When I don't specify a filter, everything works fine, but as soon as I add a filter, it no longer works, regardless of the column.

The column name is correct, everything looks OK, but it doesn't work.
If anyone has encountered this and has a solution, please let me know.

Screenshot of table definition :
<img width="1434" alt="player_table_id_column" src="https://github.com/user-attachments/assets/f07e9b2c-f19e-416e-a7f0-a3cc2d545ff6">

Thanks in advance.

**Comment by MaximeLemolt** [comment]
I solved the problem by creating a new supabase project. The filters work again without having modified the code.
I think the multiple project restarts caused problems.

I have the impression that the problem was perhaps linked to the RLS, as I notice the presence of a padlock icon next to the table name, which was no longer present on the old project despite the deactivation of the RLS.

**Old project screenshot (with the error) :**

<img width="1434" alt="player_table_id_column" src="https://github.com/user-attachments/assets/8656f205-7c11-4165-8379-0214e1c53a8f">


**New project screenshot (without the error) :**

<img width="575" alt="Capture d’écran 2024-10-15 à 13 44 02" src="https://github.com/user-attachments/assets/daa48e9c-1b0a-43eb-8e3e-9c5b52d15005">

**Comment by filipecabaco** [comment]
@MaximeLemolt that means that RLS is disabled for that specific table.

Which means that your initial error was also probably related with that. When you have RLS enabled you need to set access policies for those tables so your users can get their information from it. 

Read more about it here - https://supabase.com/docs/guides/database/postgres/row-level-security
