### ISSUE TITLE
Suggestion: document query abilities in README

### ISSUE THREAD

**Issue by rattrayalex** [supabase/realtime#132]
# Improve documentation

## Link 

The readme

## Describe the problem

As someone evaluating Supabase, I am curious how powerful the realtime capabilities are (and/or will be). A major challenge in realtime subscriptions in general is getting quick responses to complex queries. If you only want updates in very specific situations, relying on unpowerful queries can result in a large number of clients receiving a large number of irrelevant updates, which may cause production problems and high costs.

Hasura, one provider I might compare when considering Supabase, allows arbitrarily complex queries and re-runs them once per second to "implement" realtime subscriptions. This approach has obvious tradeoffs/problems/limitations.

I'd like to know how Supabase/Realtime compares – can I only query on row ID? Can I query based on equality only, or what operations are supported? Based on a single field only, or can I combine OR's and AND's? Can I only query on fields that are indexed? How are the filters implemented?

**Comment by rattrayalex** [comment]
Ah, this appears to be [documented in the supabase docs](https://supabase.io/docs/reference/javascript/subscribe#listening-to-row-level-changes): 

> You can listen to individual rows using the format `{table}:{col}=eq.{val}` - where `{col}` is the column name, and `{val}` is the value which you want to match.

**Comment by kiwicopple** [comment]
Hi @rattrayalex - I'll leave this open if you want to contribute a change to the Readme?

Otherwise let's close this :)

**Comment by rattrayalex** [comment]
Sure! Put up https://github.com/supabase/realtime/pull/133 but feel free to edit / suggest edits liberally!

**Comment by martineboh** [comment]
All examples currently listens only to a single column. Any example on listening with two or more columns like `{table}:{col}=eq.{val}:{col2)=eq.{val2}`. A use case is listening for comments that has columns is_deleted=true and author=me

**Comment by rattrayalex** [comment]
Ah, does it work with multiple columns @kiwicopple ?

**Comment by kiwicopple** [comment]
it will only work for a single column. We'll have to figure out more complicated strategies (probably as part of our workflow engine)

**Comment by w3b6x9** [comment]
@rattrayalex thanks for creating this issue and putting up PR #133!

> I'd like to know how Supabase/Realtime compares – can I only query on row ID? Can I query based on equality only, or what operations are supported? Based on a single field only, or can I combine OR's and AND's? Can I only query on fields that are indexed? How are the filters implemented?

I created PR #148 with documentation around query abilities (see: https://github.com/supabase/realtime/tree/readme#event-filters-with-examples) to start answering your questions. It's essentially what you wrote in #133 but listed with examples. Let me know what you think!

**Comment by rattrayalex** [comment]
Thanks @w3b6x9 ! That's great, though it does remain ambiguous as to whether operations other than `eq` are supported, which I would suggest clarifying.

I might also suggest including a non-point-lookup example, like `type.eq=dog` to demonstrate that there is a way to listen to many _rows_ at once (it just requires designing your db to have an appropriate lookup column).

**Comment by kiwicopple** [comment]
Hey @rattrayalex - just to answer your question directly here - only the `eq` operator is available on this server. 

We are working on some more complex use-cases in our Workflow engine, and eventually this server will be more of a "CDC" server, which picks up database changes and fires them to a "smarter" server for mapping/filtering/etc.

**Comment by rattrayalex** [comment]
@kiwicopple thanks – that's exactly what I'm hoping to be in the public docs!

**Comment by tchief** [comment]
> Hey @rattrayalex - just to answer your question directly here - only the `eq` operator is available on this server.
> 
> We are working on some more complex use-cases in our Workflow engine, and eventually this server will be more of a "CDC" server, which picks up database changes and fires them to a "smarter" server for mapping/filtering/etc.

Hey @kiwicopple, is there any news on the Workflow engine?

**Comment by kiwicopple** [comment]
Hey @tchief - the full workflow engine has been parked while we build out mult-tenant clustering, presence, and pubsub

If you're looking for extra query filters the following now work for realtime:

```
  'eq', 'neq', 'lt', 'lte', 'gt', 'gte'
```

https://supabase.com/docs/reference/javascript/using-filters

**Comment by w3b6x9** [comment]
@tchief Just wanted to clarify that the extra query filters that @kiwicopple mentioned only work in [WALRUS](https://github.com/supabase/walrus/blob/e135cf4691565d8cf40438bb3f27f527f114c72c/sql/walrus--0.1.sql#L176) at the moment. We're working hard to integrate it into Realtime. As of now, only `eq` works in Realtime.

**Comment by tchief** [comment]
@w3b6x9 Thanks for clarification!
