### ISSUE TITLE
JWKS Support

### ISSUE THREAD

**Issue by dwelch2344** [supabase/realtime#140]
# Feature request
JWT is a great way to provide security, but using a shared secret becomes a scalability pain. It'd be nice if we could configure the service to a JWKS endpoint as an alternative. 

## Additional context

JWKS builds on JWT and provides a mechanism for using pub/priv keys to sign jwts. it also allows the issuer to change rotate the signing key without invalidating the old key, and the consumers (like supabase in this case) don't need to even be aware of the change until a JWT shows up for the first time. 

Most languages have a JWKS library already built, so I'd imagine adding it wouldn't be more than a dependency and a few config lines. I personally have 0 Elixir experience, but it's been on the list for a while so if someone can point me in the right direction I could take a look :) 

Auth0 has a pretty easy breakdown of how JWKS works, and is generally where I link folks to learn more. 
https://auth0.com/docs/tokens/json-web-tokens/json-web-key-sets

**Comment by maartenvanvliet** [comment]
Fyi, Real-time uses the Joken library under the hood. 

See https://hexdocs.pm/joken_jwks/introduction.html for a library providing JWKS support for Joken

**Comment by w3b6x9** [comment]
@dwelch2344 take a look at the symmetric JWT auth PR (see: https://github.com/supabase/realtime/pull/99) and the example in Joken JWKS (see: https://github.com/joken-elixir/joken_jwks/commit/a173f643082f3d8d606f095bcf8cd20467b2eddd#diff-c971e4f3329485ad6a91eb81a345c2144a3b3eb6a035bad9f84395c1fcde24a0R49-R82).

**Comment by dwelch2344** [comment]
This looks great! Think it has what we need. Thank you!

Sorry to leave this open so long! Will give it a whirl and reopen if issues / comments / etc.

**Comment by zvictor** [comment]
Does it relate to proving a JSON Web Key Secret URI?
https://github.com/supabase/supabase/discussions/5911

**Comment by w3b6x9** [comment]
@zvictor I dropped a response here: https://github.com/supabase/supabase/discussions/5911#discussioncomment-2371302
