### ISSUE TITLE
Node.js Example Not Functioning

### ISSUE THREAD

**Issue by nickwebha** [supabase/realtime#150]
# Bug report

## Describe the bug

`examples/node-js` does not function.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone https://github.com/supabase/realtime.git`
2. `cd realtime/examples/node-js/`
3. `npm install`
4. `docker-compose up`
5. `npm start`

```
realtime_1  | 2021-05-10 21:06:17.521 [info] REFUSED CONNECTION TO RealtimeWeb.UserSocket in 121µs
realtime_1  |   Transport: :websocket
realtime_1  |   Serializer: Phoenix.Socket.V1.JSONSerializer
realtime_1  |   Parameters: %{"vsn" => "1.0.0"}
```

## Expected behavior

`npm start` connects to running docker instances of service.

## System information

- OS: Ubuntu 20.04
- Version of realtime: v0.14.0 and master (as of 2021.04.10)

## Additional context

I made sure there is no running PostgreSQL instance since the docker image seems to read from the hosts local data directory.

**Comment by nickwebha** [comment]
That fixed it. Did not expect it to be so simple.

Tested and verified working. Thank you.

**Comment by w3b6x9** [comment]
@nickwebha thanks for reporting this issue! I'm going to set `SECURE_CHANNELS: 'false'` in `docker-compose.yml` so others don't face the same issue.

**Comment by nickwebha** [comment]
FYI

I also had to do something like
```
docker run                                                       \
  -e DB_HOST='localhost'                                         \
  -e DB_NAME='postgres'                                          \
  -e DB_USER='postgres'                                          \
  -e DB_PASSWORD='postgres'                                      \
  -e DB_PORT=5432                                                \
  -e DB_IP_VERSION='IPv4'                                        \
  -e SLOT_NAME='supabase_realtime'                               \
  -e PORT=4000                                                   \
  -e SECURE_CHANNELS='false'                                     \
  -e JWT_SECRET='SOMETHING_SUPER_SECRET'                         \
  -e JWT_CLAIM_VALIDATORS='{"iss": "Issuer", "nbf": 1610078130}' \
  --network host                                                 \
  supabase/realtime
```

to get the stand-alone Docker image working. Otherwise it just errored out not being able to connect to my locally running PostgreSQL instance. I do not feel that is clear in the README.
