### ISSUE TITLE
The socket seem to not working

### ISSUE THREAD

**Issue by thuan-gempage** [supabase/realtime#153]
# Bug report
I run two examples but both seem to not working on listening to the database change.

## Describe the bug
I run `realtime` server by using this command.
```
 sudo docker run                                                       \
  --add-host=host.docker.internal:host-gateway \
  -e DB_HOST='host.docker.internal'                      \
  -e DB_NAME='postgres'                                          \
  -e DB_USER='postgres'                                          \
  -e DB_PASSWORD='1'                                      \
  -e DB_PORT=5432                                                \
  -e DB_IP_VERSION='IPv4'                                        \
  -e SLOT_NAME='supabase_realtime'                               \
  -e PORT=4000                                                   \
  -e SECURE_CHANNELS='false'                                      \
  -e JWT_SECRET='SOMETHING_SUPER_SECRET'                         \
  -e JWT_CLAIM_VALIDATORS='{"iss": "Issuer", "nbf": 1610078130}' \
  -p 4000:4000                                                   \
  supabase/realtime
```
The server still run on port 4000, however, I see a log message that appears every 5 seconds.
```
2021-05-18 15:29:52.951 [error] GenServer #PID<0.3382.0> terminating
** (stop) time out
Last message (from Realtime.Adapters.Postgres.EpgsqlServer): {:command, :epgsql_cmd_connect, %{database: "postgres", host: 'host.docker.internal', password: #Function<0.109015737/0 in :epgsql_cmd_connect.hide_password/1>, port: 5432, ssl: true, tcp_opts: [:inet], username: "postgres"}}
```

I guess the problem comes from the database connection. 

## To Reproduce

1. Run 
```
 sudo docker run                                                        \
  --add-host=host.docker.internal:host-gateway         \
  -e DB_HOST='host.docker.internal'                         \
  -e DB_NAME='postgres'                                           \
  -e DB_USER='postgres'                                           \ 
  -e DB_PASSWORD='1'                                            \
  -e DB_PORT=5432                                                  \
  -e DB_IP_VERSION='IPv4'                                      \
  -e SLOT_NAME='supabase_realtime'                      \
  -e PORT=4000                                                          \
  -e SECURE_CHANNELS='false'                               \
  -e JWT_SECRET='SOMETHING_SUPER_SECRET'                         \
  -e JWT_CLAIM_VALIDATORS='{"iss": "Issuer", "nbf": 1610078130}' \
  -p 4000:4000                                                   \
  supabase/realtime
```
2. Run `next-js` example
3. Open `next-js` website on two tab, then create a new user on one tab.
4. Refresh the other, you will see the created user.

## Expected behavior
The created user will appear on the second tab when you click `Add random user` on the first tab.

## Screenshots
Terminal screen shot.
![image](https://user-images.githubusercontent.com/73817171/118681534-dc0de480-b829-11eb-89b3-9c920ee28472.png)

## System information
- OS: Ubuntu- 20.04
- Browser: chrome
- Version of supabase-js: 1.0.7
- Version of Node.js: 14.16.0

**Comment by w3b6x9** [comment]
@thuan-gempage i use a mac and unfamiliar with ubuntu but let me investigate this for a bit!

meanwhile, can you try `--add-host=host.docker.internal:172.17.0.1` instead to see if that works? i think it comes down to the host as everything else looks good.

**Comment by w3b6x9** [comment]
@thuan-gempage what's your docker version? i think `host-gateway` is newer so it might not work for your local docker version.

making the change to `--add-host=host.docker.internal:172.17.0.1` got it working for my mac and it should work for your ubuntu.

**Comment by w3b6x9** [comment]
@thuan-gempage i just upgraded to the latest docker desktop (v3.3.3) and `--add-host=host.docker.internal:host-gateway` is now working for me.

**Comment by thuan-gempage** [comment]
@w3b6x9 I still get that error. I also tried with `DB_HOST='172.17.0.1'` and it does not work.

**Comment by w3b6x9** [comment]
@thuan-gempage hmm what's your docker version? Also, are you sure your local postgres is running via docker? Can you walk me through how you set up the db on your machine?

**Comment by thuan-gempage** [comment]
@w3b6x9 I fixed it. It seems like the `DB_HOST='172.17.0.1'` not working on Ubuntu. So I added `--network="host"` option and change the `DB_HOST` to `127.0.0.1`, and it worked.
Thank you so much for helping me!

**Comment by w3b6x9** [comment]
@thuan-gempage nice, glad you got it working!
