### ISSUE TITLE
When Stable release will be released

### ISSUE THREAD

**Issue by arunjoshtech** [supabase/realtime#156]
Dear Team,
When you are planning to release production ready?

# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by kiwicopple** [comment]
Hey @arunjoshtech - this is technically ready for production. We are using it in thousand of projects in Supabase already.

The reason we aren't going to update the Beta tag is:

- we aren't providing full support and SLAs yet
- we may change the structure of it in the future to be even more scalable. we haven't finalised the structure of this yet

If this suits your current use-case, it's relatively stable. (especially once [this](https://github.com/supabase/realtime/pull/152) PR is merged, it should be able to handle ~1 million inserts on a small EC2 instance)
