### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#16]
User should be able to use postgres row level security.

Possible approach:
- follow postgrest authentication
- give customer ability to pass through their own keys/spec
- do this on our own API gateway (won't work for self hosted) <--- favourite for now

```
supabase
.from('analytics')
.subscribe('users', 3, 'token', {...})
```

**Comment by kiwicopple** [comment]
moved discussion here: https://github.com/supabase/supabase/issues/64

**Comment by kiwicopple** [comment]
related: https://github.com/supabase/supabase/issues/64

**Comment by kiwicopple** [comment]
Closing this and tracking it in our main repo for a single location discussion
