### ISSUE TITLE
Won't connect to WS 404 not found

### ISSUE THREAD

**Issue by DAmisonSSG** [supabase/realtime#165]
# Bug report

The websocket will not connect via the @supabase/realtime-js it gives the following error on the server

```
realtime_1  | 2021-07-20 13:58:57.601 request_id=FpOEdyEIa3CFweMAAAEi [info] GET /websocket
realtime_1  | 2021-07-20 13:58:57.601 request_id=FpOEdyEIa3CFweMAAAEi [info] Sent 404 in 576µs
realtime_1  | 2021-07-20 13:59:16.544 request_id=FpOEe4oiIQHZ7twAAAAj [info] GET /socket
realtime_1  | 2021-07-20 13:59:16.544 request_id=FpOEe4oiIQHZ7twAAAAj [info] Sent 404 in 486µs
```
going to http://192.168.1.7:4000 shows 'Supabase Realtime See details at supabase.io as expected'

Used in react JS to connect as follows

```
import './App.css';
import { RealtimeClient } from '@supabase/realtime-js'


function App() {

  var socket = new RealtimeClient('wss://192.168.1.7:4000')
  socket.connect()

  return (
    <div className="App">
      Test DB
    </div>
  );
}

export default App;
```

**Comment by w3b6x9** [comment]
@DAmisonSSG 404 might point to your websocket URL passed to `RealtimeClient` in secure mode. Can you try `'ws://192.168.1.7:4000'` and see if that works?

**Comment by ChronSyn** [comment]
> @DAmisonSSG 404 might point to your websocket URL passed to `RealtimeClient` in secure mode. Can you try `'ws://192.168.1.7:4000'` and see if that works?

I'm having the same issue as the OP using the same code. Unfortunately, the same issue remains even when trying `ws` instead of `wss`:
```
2021-07-21 19:16:51.908 request_id=FpPkZMetoR-95O8AAADx [info] GET /websocket
2021-07-21 19:16:51.909 request_id=FpPkZMetoR-95O8AAADx [info] Sent 404 in 513µs
2021-07-21 19:21:42.116 request_id=FpPkqFlfyYo9fZ8AAAEB [info] GET /websocket
2021-07-21 19:21:42.116 request_id=FpPkqFlfyYo9fZ8AAAEB [info] Sent 404 in 587µs
2021-07-21 19:21:43.180 request_id=FpPkqJjMQ_4jqIMAAAER [info] GET /websocket
2021-07-21 19:21:43.180 request_id=FpPkqJjMQ_4jqIMAAAER [info] Sent 404 in 701µs
```

Adding an `onError` handler doesn't provide much insight from what I can see:
```
err: _Event {
    type: 'error',        
    isTrusted: false,     
    _yaeti: true,
    target: W3CWebSocket {
      _listeners: {},
      addEventListener: [Function: _addEventListener],
      removeEventListener: [Function: _removeEventListener],
      dispatchEvent: [Function: _dispatchEvent],
      _url: 'ws://<redacted>:4000/websocket?vsn=1.0.0',
      _readyState: 3,
      _protocol: undefined,
      _extensions: '',
      _bufferedAmount: 0,
      _binaryType: 'arraybuffer',
      _connection: undefined,
      _client: [WebSocketClient],
      onopen: [Function (anonymous)],
      onerror: [Function (anonymous)],
      onmessage: [Function (anonymous)],
      onclose: [Function (anonymous)]
    },
    cancelable: true,
    stopImmediatePropagation: [Function (anonymous)]
  }
```

**Comment by w3b6x9** [comment]
@ChronSyn thanks for confirming. Will look into this shortly.

**Comment by w3b6x9** [comment]
@DAmisonSSG @ChronSyn there are two other additions to make besides the `wss` -> `ws` change in order to get it working:

- append `/socket` to the ws url.
- make sure to run docker with `SECURE_CHANNELS` set to `'false'`.

here's what i did to get it up and running on my mac:

```
docker run                                  \
  -e DB_HOST='docker.for.mac.host.internal' \
  -e DB_NAME='postgres'                     \
  -e DB_USER='postgres'                     \
  -e DB_PASSWORD='postgres'                 \
  -e DB_PORT=5432                           \
  -e PORT=4000                              \
  -e JWT_SECRET='SOMETHING_SUPER_SECRET'    \
  -e SECURE_CHANNELS='false'                \
  -p 4000:4000                              \
  supabase/realtime
```

```
new RealtimeClient('ws://localhost:4000/socket')
```

I'm going to update both `realtime` and `realtime-js` READMEs in order to reflect what I've posted here. Let me know if the above fixes it for you. Thanks!

**Comment by ChronSyn** [comment]
> @DAmisonSSG @ChronSyn there are two other additions to make besides the `wss` -> `ws` change in order to get it working:
> 
> * append `/socket` to the ws url.
> * make sure to run docker with `SECURE_CHANNELS` set to `'false'`.

Appending `/socket` was the solution for me (though I had `SECURE_CHANNELS` set to false already).

I think I got a bit confused because I forgot that the supabase-js lib connects to the kong instance, which routes via `/websocket`.
