### ISSUE TITLE
Realtime APIs don't correctly parse arrays in response

### ISSUE THREAD

**Issue by fenix-hub** [supabase/realtime#167]
# Bug report

This bug was originally reported in Discord, so maybe you are already investigating on this, but now the channel is very populated.

## Describe the bug
Messages coming from Realtime APIs, subscribing to a Phoenix Channel, don't correctly parse Arrays as expected.
Arrays define in Tables, f.i. as `text[]` (`media_attached:["media1.png", "media2.png"]`, are parsed inside messages coming from Realtime APIs as fake arrays consisting in a single String, without a proper format following any specificatio, f.i. `media_attached:"{"media1.png", "media2.png"}"`.

## To Reproduce

1. Create a Table
2. Define a column as a `text[]` text array
3. Subscribe to INSERTS on this table with Realtime APIs
4. Insert a new record in the table, with a value for the `text[]` column as `["text1","text2"]`
5. Receive the message form Realtime APIs and take a look at how the column value is parsed

## Expected behavior

Realtime APIs should correctly parse arrays if they are defined such in a table.

## Screenshots

![chrome_6kCXrtDo5m](https://user-images.githubusercontent.com/45271396/127181115-7e7fa948-6835-4b55-a6e2-81b7e2eb0ae0.png)
An example of table, used to test this bug

![chrome_kuiMpEjeo3](https://user-images.githubusercontent.com/45271396/127181456-21120930-32dc-4dc5-a073-bd3b90ec23bf.png)
A sample response received through rest apis.

## System information

- OS: Windows 10
- Browser (if applies) [e.g. chrome, safari]
- Library : godot-engine.supabase (gdscript)

**Comment by w3b6x9** [comment]
@fenix-hub I'm currently looking into this issue and just wanted to confirm that when you write "Realtime APIs" do you mean `RealtimeClient` from [realtime-js](https://github.com/supabase/realtime-js)?

The Supabase client ([supabase-js](https://github.com/supabase/supabase-js)) is actually where the conversion is being done (see: https://github.com/supabase/supabase-js/blob/master/src/lib/SupabaseRealtimeClient.ts#L19).

If you're using the `RealtimeClient` directly, you can call the `Transformers.convertChangeData` function to transform array types like `"{"media1.png", "media2.png"}"` to `["media1.png", "media2.png"]`.

**Comment by w3b6x9** [comment]
@fenix-hub I just saw your Discord message about this issue, and unfortunately we aren't performing conversions on the `Realtime` server itself (see this [issue](https://github.com/cainophile/pgoutput_decoder/issues/1) for more context). We're actually doing this on the client (see `realtime-js` [transformers](https://github.com/supabase/realtime-js/blob/master/src/lib/transformers.ts) `realtime-dart` [transformers](https://github.com/supabase/realtime-dart/blob/main/lib/src/transformers.dart) as examples). I think you'll have to do the conversions in your `godot-engine.supabase` library for now. It's not ideal but we're currently working on improving `Realtime` server and will discuss doing the conversions once server-side so all clients can benefit.

**Comment by fenix-hub** [comment]
@w3b6x9 Thank you for your reply.
It's ok for me to do conversions client side, but I would suggest to consider server-side conversions anyway, since it is the only way to give homogeneous functionalities among all clients, regardless of the library used, because of several reasons.
You can close this if you want, thanks again for your explanation about the behaviour. :)
