### ISSUE TITLE
NodleDosh

### ISSUE THREAD

**Issue by twins2020** [supabase/realtime#169]
# Feature request

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

**Comment by w3b6x9** [comment]
@twins2020 please create a new issue with the details filled in.

**Comment by twins2020** [comment]
0x1e1922ed3570839a4764c59d9c82d25e9d73029bd4f0cd4a59cf9a2afbef5d35/0xf515F1D656E550E889441D05399ff1Ea9b551592
