### ISSUE TITLE
Disable realtime by default?

### ISSUE THREAD

**Issue by dbi1** [supabase/realtime#176]
Hello,

In the UI, you have the following note about realtime:

> The realtime server doesn't provide per-user security. Until we build a more robust auth system for websockets, you shouldn't use realtime on any client which is exposed to users.
> 
> For security purposes, you can run begin; drop publication if exists supabase_realtime; create publication supabase_realtime; commit;. This creates a publication which is not subscribed to any table and completely disables realtime updates on the Supabase client.
> 

Given this, wouldn't it be better if the default state for realtime were "off" (i.e. disabled) for new projects/tables, with the option of manually enabling it instead?

I could easily see myself creating a new Supabase project, setting RLS on my table, and forgetting that realtime is enabled...

Thank you!

P.S.: Really, really appreciate the work you guys are doing on Supabase :)

**Comment by w3b6x9** [comment]
@dbi1 

> wouldn't it be better if the default state for realtime were "off" (i.e. disabled) for new projects/tables, with the option of manually enabling it instead?

This is exactly the case!

When you create a Supabase project, Realtime is not activated for any tables. You can then go to the Supabase Dashboard and manually turn it on for each table or all tables.

We're currently working on applying RLS to Realtime and will notify the community when this is launched. You can check out https://supabase.io/blog/2021/09/10/supabase-beta-august-2021#realtime-security-codename-walrus to learn more about the initiative.
