### ISSUE TITLE
Realtime updates for views

### ISSUE THREAD

**Issue by alator21** [supabase/realtime#188]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to receive real-time updates for views(e.g i have a view that is the result of the junction of two tables. I would like to receive updates when the  rows of the view are inserted/updated/deleted)

## Describe the solution you'd like

I would like to use the `.on` supabase js client function with a view and get realtime updates

**Comment by w3b6x9** [comment]
@alator21 Realtime works by getting changes from Postgres logical replication, which only applies to database tables. I'm not sure how feasible this is but perhaps you can use Postgres triggers to dump changes from both tables into another table and listen for changes on that table.

I'll leave this open for now and see if anyone in the community has any viable solutions.

**Comment by osaxma** [comment]
By the way, I've a discussion open regard this topic here -- mainly for schema isolation and views composed of multiple tables (i.e. to avoid listening to a base table and then fetching from the view):
- https://github.com/supabase/supabase/discussions/5152
