### ISSUE TITLE
Subscribing to materialized views (like Hsaura, RethinkDB and Firebase Realtime DB)

### ISSUE THREAD

**Issue by jamieflorence** [supabase/realtime#191]
# Feature request

Howdy. I’ve been searching for a plausible Firebase alternative for a while now, and am delighted to have stumbled across this.

Before I get too excited, I have one quick question: is there any way to subscribe to a materialized view, rather than a table?

For context, I currently receive real time data which I put through a long computational pipeline to produce a summary table. The data comes in large packets at irregular intervals. I only care about the summary output in real time, not the individual data inputs, so I just want to be able to subscribe over websockets so I can build a dashboard.

Is this, or something like this, possible with supabase?

Hasura is able to, but their model uses live queries, and the computational model I have is far too intensive for that; I want to be able to trigger the refresh rate as data comes in.

**Comment by w3b6x9** [comment]
this was discussed here: https://github.com/supabase/supabase/discussions/3824
