### ISSUE TITLE
RLS and Realtime does not work for tables with `jsonb` fields

### ISSUE THREAD

**Issue by madebyfabian** [supabase/realtime#207]
# Bug report

## Describe the bug

I have some issues with the new Realtime on RLS Tables Feature. I setuped all the RLS stuff and it works perfectly on almost all my tables. Really awesome! With create, update, delete updates.

But, for one table, which has a jsonb field in it, it just completely doesn't work and throws multiple errors after every change. It even kicks me off the websocket connection after the errors happen. 

On the initial connection itsself, everything works. But as soon as the content changes, I get these errors in the JavaScript Console (in the session that subscribed and should receive the changes):

```
Could not convert cell of type jsonb and value [object Object]
This is the error: SyntaxError: Unexpected token o in JSON at position 1
```
These errors are thrown from JS files provided by the supabase extension, so it's not my code throwing them. (thrown by `transformers.ts` and `browser.js`)

after this happens, the websocket connection just completely closes and the console shows:

```
WebSocket connection to 'wss://uzmluoivxnndbkjoajhn.supabase.co/realtime/v1/websocket?apikey=MY_API_KEY_IS_HERE&vsn=1.0.0' failed: 
```

Am I missing something? Is Realtime not working for jsonb fields yet? Or is this a known bug somehow. 

Thanks for your help in advance! 

## To Reproduce

1. Create a table that has at least one jsonb field in it.
2. Create a row and fill the jsonb field with some dummy json object data
2. Create a simple RLS rule, for example `(uid() = my_id)`
3. Connect to the table like in the docs
```js
const mySubscription = supabase
  .from('my_table')
  .on('*', payload => {
    console.log('Change received!', payload)
  })
  .subscribe()
```
5. Do any change on the table and wait for the handling to happen.

## Expected behavior

No errors for tables with jsonb fields, and not getting kicked off by the websocket after a few seconds after these errors appear.

## System information

- OS: macOS
- Browser (if applies): Chrome 96
- Version of supabase-js: 1.23.0
- Version of Node.js: 15.8.0

**Comment by w3b6x9** [comment]
@madebyfabian yes, this is a known issue. The fix has been merged (see [PR](https://github.com/supabase/realtime/pull/203)) and we're going to deploy this to all Supabase projects very soon.

**Comment by madebyfabian** [comment]
@w3b6x9 Wow, that was a lightspeed-answer! Thank you so much, this info really helps me. And great that there is a fix soon, so I can start reworking my app to use Realtime. I'll close this issue then.

**Comment by w3b6x9** [comment]
@madebyfabian if you're blocked in the meantime please send an email to support@supabase.io with your project ref and a link to this issue and we can roll back your Realtime version temporarily so you're unblocked. This would mean no RLS support for a brief period of time.

**Comment by madebyfabian** [comment]
@w3b6x9 Thank you for the offer, but I think I will just continue work on another part of the app while waiting.
