### ISSUE TITLE
Chore: update Github description to supabase.com

### ISSUE THREAD

**Issue by Isaiah-Hamilton** [supabase/realtime#208]
# Chore

## Describe the chore

update Github description  from [supabase.io](https://supabase.com) to [supabase.com](https://supabase.com)

<img width="1392" alt="Screen Shot 2021-12-16 at 3 15 56 PM" src="https://user-images.githubusercontent.com/70828596/146443104-c731b7cd-8edd-4d9a-bcf9-408fcf12602e.png">

**Comment by darora** [comment]
Fixed, thanks
