### ISSUE TITLE
Improve documentation: `DELETE` events don't work for Realtime Row-Level Subscriptions while `REPLICA IDENTITY` is not `FULL`

### ISSUE THREAD

**Issue by madebyfabian** [supabase/realtime#212]
# Improve documentation

## Link 

https://supabase.com/docs/reference/javascript/subscribe

## Describe the problem

Hello together, merry christmas for those who celebrate! 🎄🎄

I just found out after a long debugging-session, that when creating a realtime subscription with a low-level selector onto a table that doesn't have `REPLICA IDENTITY` on `FULL`, that for rows that are being created after the connection is made, only `INSERT` and `UPDATE` events get fired for these new rows, but no `DELETE` events. My code was like:

```js
await supabase
  .from(`collections:is_hidden=eq.false`)
  .on('*', payload => collectionsStore.handleRealtimeEvent(payload))
  .subscribe()
```

and `INSERT` and `UPDATE` would get fired for the new rows, but not `DELETE`.

## Describe the improvement

The improvement would be to add some more description/a warning that tells you you have to have `REPLICA IDENTITY` on `FULL` when you want to use row-level subscriptions and listen to the `DELETE` event for newly created rows.

## System information

- Version of supabase-js: 1.29.1

**Comment by tconroy** [comment]
It seems the docs [already state this](https://supabase.com/docs/reference/javascript/subscribe#listening-to-deletes)?
> #### Listening to deletes
> By default, Supabase does not send deleted records. If you want to receive the deleted record you can enable full replication for the table you are listening too:
> `alter table "your_table" replica identity full;`

**Comment by madebyfabian** [comment]
@tconroy Thanks for your answer! Have read the docs many times but somehow haven’t seen this part. Will close this then.
