### ISSUE TITLE
error occurred when joining <channel> with user token

### ISSUE THREAD

**Issue by neilkinnish** [supabase/realtime#217]
# Bug report

Have secure channels turned on with JWT and this has been working fine for some time (sending the JWT in as param apikey).

However, following a recent update to the realtime server project we are now getting an error joining channels:

`error occurred when joining <channel> with user token`.

I have updated the JS client and attempted to use the JWT as the `user_token` but this had no effect.

I may be missing something obvious but the docs were not immediately clear and I couldn't find any additional info related to this error.

## Additional context

`
{"event":"phx_reply","payload":{"response":{"reason":"error occurred when joining realtime:<redacted> with user token"},"status":"error"},"ref":"3","topic":"realtime:<redacted>"}
`

**Comment by neilkinnish** [comment]
Ah, just noticed the RLS section which I missed previously. Apologies.

**Comment by neilkinnish** [comment]
Just wanted to double check expected behaviour.... if `REPLICATION_MODE='STREAM'` and `SECURE_CHANNELS='true'` should we be getting an error joining channels: `error occurred when joining realtime:<redacted> with user token`?

**Comment by w3b6x9** [comment]
@neilkinnish yes, user token is an alias for the JWT you passed when connecting to the socket in `STREAM` mode. As long as the JWT is valid you should be able to successfully connect.

**Comment by Donnerstagnacht** [comment]
I updated to javascript-v2 client and get a similar error - except the part with jwt token is missing. Any ideas why this might occur or how to fix it? 

`{event: "phx_reply",…}
event
: 
"phx_reply"
payload
: 
{response: {reason: "error occurred when joining realtime:public:profiles_counters"}, status: "error"}
response
: 
{reason: "error occurred when joining realtime:public:profiles_counters"}
reason
: 
"error occurred when joining realtime:public:profiles_counters"
status
: 
"error"
ref
: 
"1"
topic
: 
"realtime:public:profiles_counters"`
