### ISSUE TITLE
Support more filters in addition to `eq`

### ISSUE THREAD

**Issue by osaxma** [supabase/realtime#222]
# Feature request

Support: `neq`, `lt`, `lte`, `gt`, and  `gte` in addition to `eq`. 

## Use case
In my app, I'm trying to filter realtime using `(realtime:public:some_table:someValue=gt.previousValue)` but that's currently not possible.  

## Describe the solution you'd like

I would like to be able to use:  `neq`, `lt`, `lte`, `gt`, and  `gte` to filter realtime data.

## Additional context

The issue was originally filed here: 
 - supabase-community/supabase-flutter#91

**Comment by w3b6x9** [comment]
Related: https://github.com/supabase/walrus/issues/9

**Comment by osaxma** [comment]
@w3b6x9 

It looks like `neq`, `lt`, `lte`, `gt`, and `gte` are already supported by walrus according this comment: 
- https://github.com/supabase/walrus/issues/9#issuecomment-1018927685

But it isn't supported by realtime according to this: 
- https://github.com/supabase-community/supabase-dart/issues/90#issuecomment-1018324651

**Comment by w3b6x9** [comment]
@osaxma walrus does support them but realtime rls server does not expose those additional filters at the moment.

**Comment by w3b6x9** [comment]
support contained in (cd) filter issue: https://github.com/supabase/realtime/issues/233

**Comment by RasmusEdvardsen** [comment]
Is there anything we can do to help @w3b6x9?

**Comment by w3b6x9** [comment]
@RasmusEdvardsen thanks for offering! We're currently making some big changes to Realtime and will add in additional filters shortly after the new changes we're making are stable.

**Comment by RasmusEdvardsen** [comment]
@w3b6x9 good to hear 🙂
Thanks for the feedback, I really like your product!

**Comment by Marviel** [comment]
I think that when this is complete, it will really help https://github.com/psteinroe/supabase-cache-helpers/pull/22/files come into its own for React users :)

**Comment by chasers** [comment]
Update ... this is done actually, and pending some QA we will update the docs and let you know so you can take a look!

**Comment by Marviel** [comment]
@chasers is this planned on being released soon? We're hitting our channel limits currently because we can only do direct queries

**Comment by chasers** [comment]
Per our discussion offline, these are actually on production now and more obvious with #373

**Comment by LorenzFedeli** [comment]
will eq filter also suport Strings?

**Comment by Marviel** [comment]
@LorenzFedeli in my experience yes

**Comment by chasers** [comment]
@LorenzFedeli yes it does.

**Comment by LorenzFedeli** [comment]
im talking about .from('table:name=eq.Test') for me this dose not work only comparing to id works

**Comment by chasers** [comment]
Can you try it with a normal string and see what happens?  Comparing to a datetime field would likely be an edge case currently. 

And if you're hosted on our platform it's usually easier if I can get a project ref. You can [contact support](https://app.supabase.com/support/new) with those details and we can take it from there if you like.

**Comment by KiddoV** [comment]
Was supporting contains `.cs` filter ever make it to production?
