### ISSUE TITLE
policy accessing `user_metadata` is not working with realtime only

### ISSUE THREAD

**Issue by osaxma** [supabase/realtime#224]
# Bug report

## Describe the bug

I've the following policy defined on a table:

```sql
CREATE POLICY events_policy
ON public.events
FOR SELECT USING (
  auth.profile_id() = profile_id
);
```

where `auth.profile_id()` is defined as follow:

```sql
CREATE OR REPLACE FUNCTION auth.profile_id() RETURNS int LANGUAGE sql STABLE AS $function$
    select
        (((current_setting('request.jwt.claims', true)::jsonb) ->> 'user_metadata')::jsonb ->> 'profile_id')::int
  $function$;
```
> `profile_id` is added to `auth.users.raw_user_meta_data` upon profile creation

When I access the data using `postgrest`, the policy works fine and I'm able to retrieve the data. Though when I listen to the data using `realtime`, I don't get any result.

When I added the `auth.users.id` to the table and updated the policy as shown below, the `realtime` worked fine

```sql
CREATE POLICY events_policy
ON public.events
FOR SELECT USING (
  auth.uid() = auth_id
);
```

This made me assume that the `user_metadata` is not available for some reason with realtime but I'm not quite sure. I tried to debug the issue but I actually didn't know how (I'd appreciate any tips here). 

## Additional context

I'm observing this using the cli  (latest version: 0.16.1) which seems to be using [`supabase/realtime:v0.19.5`](https://github.com/supabase/cli/blob/c7472d868d6658b8999f49dfd5fcff5e3a185703/internal/utils/utils.go#L46) version of the realtime image. 

Please let me know if you need any further details.

**Comment by w3b6x9** [comment]
@osaxma ah, you need `supabase/realtime` version >= 0.20.0 for your `events_policy` policy to work. i'll go and update the version in `cli`.

**Comment by osaxma** [comment]
Thanks a lot @w3b6x9 🙏🏽
