### ISSUE TITLE
Realtime does not work with RLS and service role(key)

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime#226]
# Bug report

Using a service role key normally bypasses RLS.  With realtime using the service role key uses RLS.
It is not clear if this is supposed to work or not, at least I have not found documentation on it.
Users on Discord are attempting this and asking why it does not work.

## To Reproduce

I verified their issue by using service role to init the client (yes I did the test on a browser).
A table with RLS off works.
Change the select policy to false and realtime does not trigger on changes.
Change the select policy to auth.role() = 'authenticated' and it does work.

## Expected behavior

If service role is supposed to work it should bypass RLS.

## System information
Latest Instance and supabase.js

**Comment by GaryAustin1** [comment]
In thinking about it, you are only supposed to run service role on a server.  I did the test on a client with browser as I am not familiar with using Supabase on a server.  Does realtime websocket protocol even work on a server as the client?

**Comment by kiwicopple** [comment]
Thanks for the detailed issue @GaryAustin1 

>  Does realtime websocket protocol even work on a server as the client?

Yes, this should work too 👍

**Comment by w3b6x9** [comment]
@GaryAustin1 thanks, will try and reproduce this now.

**Comment by w3b6x9** [comment]
@GaryAustin1 your project(s) were upgraded to the newest Realtime RLS version in the last 12 hours or so. This version enables Realtime RLS to work with other database roles like `service_role` and `anon`. Can you please try again?

**Comment by GaryAustin1** [comment]
It does not work on  my project ending in wplM which is just a test project and very recent instance.
Sames symptoms as above from a browser using service key.

**Comment by w3b6x9** [comment]
@GaryAustin1 got it. checking now.

**Comment by w3b6x9** [comment]
@GaryAustin1 can you please email support@supabase.io with the full project ref? i'll investigate immediately.

**Comment by GaryAustin1** [comment]
Yeah I'll send it, but I screwed up with the digits above and those were last 4 of the service key...

**Comment by GaryAustin1** [comment]
> This version enables Realtime RLS to work with other database roles like service_role and anon
Just to make sure the issue I'm reporting is the service_role is honoring the RLS (authenticated works and false does not), but for service_role the RLS should be ignored...

**Comment by w3b6x9** [comment]
@GaryAustin1 here's what i just did:

1. created a new supabase project, created a test table and enabled RLS, added table to `supabase_realtime` publication.
2. created client with `service_role` key.
3. inserted into test table and client received the change.
4. created policy on test table and set to `false`, inserted again into test table, and client received the change.

**Comment by GaryAustin1** [comment]
Just sent you email with images of setup.  Run about 10  minutes ago.

**Comment by GaryAustin1** [comment]
Not sure this is of any use, but the realtime table when using service_role:
![image](https://user-images.githubusercontent.com/54564956/151886693-7fee9efb-907d-438e-b772-6d35984f793e.png)

**Comment by w3b6x9** [comment]
@GaryAustin1 looks like you used the `authenticated` token instead of the `service_role` token. can you please confirm that the token you're using to test has `role` of `service_role`?

also, we never received your email.

**Comment by w3b6x9** [comment]
@GaryAustin1 

>  not sure if that is left over from a previous test

that record should have been deleted the moment the authenticated user disconnected

**Comment by GaryAustin1** [comment]
resent email...  It is for sure the service_role key and included all codes in the email.
I deleted the only user so now have no users.  The realtime subscriptions still has that user in it and no other for the service role.

**Comment by GaryAustin1** [comment]
So with no users in the user table, and a refresh of the client, there is a new connection id, but the user is still the one I used to have, but is not in the user table anymore...
Not sure this is chasing something else at this point or related...

{"aud":"authenticated","exp":1643672238,"sub":"dd3ff6ed-50b1-4c28-98ba-481a6d6c8dda","role":"authenticated","email":"gabbott@xxxxxxxx.com","phone":"","app_metadata":{"provider":"email","providers":["email"]},"user_metadata":{}}

**Comment by GaryAustin1** [comment]
OK so I cleared the local storage AND now the service key works.....

**Comment by w3b6x9** [comment]
@GaryAustin1 I was just about to write that it's b/c you were testing with an `authenticated` user and that it persisted. Every subsequent subscription Realtime RLS used the `authenticated` user and not the `service_role` role.

By default, `supabase-js` client connects to the Realtime RLS socket using the supabase key you pass in when initializing. Normally it's the `anon` token but in your case it's the `service_role` token. If you, or one of your users, haven't signed in yet then you would create subscriptions using the supabase key (`anon` or `service_role`). Once you do sign in, you're an `authenticated` user and when you create subscriptions then Realtime RLS receives the `authenticated` token.

**Comment by GaryAustin1** [comment]
Yeah, either they did the same test thing, or they had the real problem with their instances not being updated...
I'll mention to them using the service_key_role is not a normal thing to do on a client (as I said at start of this issue).
Thanks!

**Comment by w3b6x9** [comment]
@GaryAustin1 awesome, thanks for updating everyone!

**Comment by jackmerrill** [comment]
Hey there @w3b6x9! I'm having the same issue on the server-side with a service role key, I've restarted my project's server and still don't receive realtime updates on the server (Node.js script basically).

**Comment by w3b6x9** [comment]
@jackmerrill have you added tables to the publication?

**Comment by jackmerrill** [comment]
Disregard, I didn't have replication enabled. Thanks anyways!

**Comment by GaryAustin1** [comment]
@w3b6x9 No offense to jack but that was the first question I asked him a few days ago, just got lost in the shuffle and I asked him again a few minutes at same time you were posting here...  SIGH.
BUT you keep saying "added to publication"  I think most only know the replication tab so that could be confusing...

**Comment by w3b6x9** [comment]
@GaryAustin1 

> BUT you keep saying "added to publication" I think most only know the replication tab so that could be confusing...

thanks, this is good feedback. i'll make sure to reference the replication settings moving forward to prevent further confusion.

> is it possible for subscribe to error if replication not on for that Table?

someone else actually created a github issue for this: https://github.com/supabase/realtime/issues/205.
