### ISSUE TITLE
server does not acknowledge `access_token` update

### ISSUE THREAD

**Issue by osaxma** [supabase/realtime#227]
# Bug report

## Describe the bug

When sending an `access_token` update for a specific topic, the server does not acknowledge the event.

## To Reproduce
- connect to the server using websocket
- subscribe to a topic:
  ```
  [client to server] >>> {topic: <some_topic>, event: phx_join, payload: {user_token:  <token>}, ref: 1}
  [server to client] <<<  {event: phx_reply, payload: {response: {} , status: ok}, ref: 2, topic: <some_topic>}
  ```
- update the access token:
  ```
  [client to server] >>> {topic: <some_topic>, event: access_token, payload: {access_token: <new_acccess_token>, ref: 2}
  [server to client] <<< # no acknowledgement from server here
  ```

## Expected behavior
I expect an acknowledgment  such as:
```
{event: phx_reply, payload: {response: {} , status: ok}, ref: 2, topic: <some_topic>}
```

## Additional Context
This behavior is observed with `supabase/realtime:v0.21.0` image.

**Comment by w3b6x9** [comment]
@osaxma good feedback!

how would you utilize the server acknowledgement? for example, would you try to send the access token again if you didn't receive an ack within n seconds?

**Comment by osaxma** [comment]
> how would you utilize the server acknowledgement? 
Mainly an assurance. 

My line of thoughts was if I don't receive an acknowledgement, I'd send a heartbeat to check if the connection is live and reconnect if necessary. 

Though as I'm thinking about it now, this only covers a rare case when the JWT expires & the connection is lost between heartbeats (within a 30 second window in my case). So it's not an issue that I faced.

**Comment by w3b6x9** [comment]
@osaxma

> if I don't receive an acknowledgement, I'd send a heartbeat to check if the connection is live and reconnect if necessary.

Gotcha! You can pass a callback function to `subscribe()` and it'll invoke the callback with `'SUBSCRIPTION_ERROR'` and the error, at least this is true for `supabase-js`, and then you can re-subscribe if you'd like.

My hesitation with sending a reply in this scenario is that it'll block the pipe, as the more subscriptions you have on a client the more replies the socket connection will have to send through.

I'm going to close this for now but if you find a use case without another workaround then we can further discuss this.

Thanks for bringing this up!
