### ISSUE TITLE
Support more postgres operators for realtime filtering

### ISSUE THREAD

**Issue by RasmusEdvardsen** [supabase/realtime#233]
# Feature request
Support for more filtering on the **from** clause, when creating listeners.

## Is your feature request related to a problem? Please describe.
This feature request is a matter of performance.

## Describe the solution you'd like
Say I'd like a listener to listen to **C**r**UD**events on user A's friends. I would like to just listen to all users, who have user A's id in their friends column.

## Describe alternatives you've considered
My current alternative is to listen to user A's friends list, which changes only on creations/deletions (not updates) of users that are friends with user A.

This could be achieved by using something like the following:
```
return supabase
    .from<User>(`users:id=cd.{${user.id}}`)
    .on('*', async payload => {
        // callback
    })
    .subscribe()
```

As shown above, the cs (contains) operator could be used here. This is documented here: [Postgres operators](https://postgrest.org/en/latest/api.html#operators)

## Additional context
My current workaround does not satisfy the needs of my solution, and will further not satisfy future needs, which will involve user location updates.
Not only that, I imagine listening on entire table changes is not very performant.

Thanks for this awesome project you are building,
Rasmus

**Comment by w3b6x9** [comment]
@RasmusEdvardsen thanks for requesting the `cs` filter. i've linked it to https://github.com/supabase/realtime/issues/222 and will close this issue.

**Comment by KiddoV** [comment]
Will `.cs` filter ever make it to production?
