### ISSUE TITLE
supabase-realtime causes high CPU load

### ISSUE THREAD

**Issue by micheljung** [supabase/realtime#237]
# Bug report

## Describe the bug

There are no queries, yet:

```
CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O   PIDS
8e46d372f34f   supabase-realtime   3.14%     91.47MiB / 25.01GiB   0.36%     558kB / 343kB   0B / 0B     37  
3b13fd22c275   supabase-db         12.25%    72.86MiB / 25.01GiB   0.28%     330kB / 111kB   0B / 0B     11  
```

## To Reproduce

1. Clone https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml
2. `docker-compose up -d db realtime`
3. `docker stats`

## Expected behavior

Both containers should be idle and cause almost no CPU load.

## System information

- OS: Windows (Docker Desktop)

## Additional context:

Once you terminate supabase-realtime, the CPU is idle:

```
CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O   PIDS
3b13fd22c275   supabase-db   0.02%     70.45MiB / 25.01GiB   0.28%     2.85MB / 586kB   0B / 0B     10  
```

**Comment by w3b6x9** [comment]
@micheljung this is the expected side effect of running Realtime RLS b/c it's polling the database every 100 milliseconds. Depending on your needs, you can change the poll rate or use the non-RLS version (set `REPLICATION_MODE` to `STREAM`) for lower CPU usage.
