### ISSUE TITLE
Connecting to a distant RDS seems to fail

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#24]
With my local machine in Singapore, I couldn't get this to connect to an RDS instance in the US.

Steps to replicate:

1. Go to RDS (somewhere far away)
1. Go to Parameter groups
1. Create a Postgres11 parameter group, and set the rds.logical_replication to `1`
1. Create a new RDS (free tier is fine). 
1. Update the Security Group to be fully permissive - allow all IP's (just to be safe)
1. Try to run this app with the connection info. Eg, move into the `server` folder and run:

```sh
DB_HOST=instance-name.accountid.us-west-1.rds.amazonaws.com \
DB_NAME=postgres \
DB_USER=postgres \
DB_PASSWORD=postgres \
DB_PORT=5432 \
APP_PORT=4000 \
APP_HOSTNAME=localhost \
SECRET_KEY_BASE=SOMETHING_SECRET \
DB_SSL=true \
mix phx.server
```

This will probably fail with the following error:

```sh
[info] Running RealtimeWeb.Endpoint with cowboy 2.6.3 at 0.0.0.0:4000 (http)
[info] Access RealtimeWeb.Endpoint at http://localhost:4000
[info] Application realtime exited: Realtime.Application.start(:normal, []) returned an error: shutdown: failed to start child: Realtime.Replication
    ** (EXIT) :invalid_authorization_specification
** (Mix) Could not start application realtime: Realtime.Application.start(:normal, []) returned an error: shutdown: failed to start child: Realtime.Replication
    ** (EXIT) :invalid_authorization_specification
```

However if you try to connect with something like PG Admin it will succeed.

**Comment by kiwicopple** [comment]
epgsql (https://github.com/epgsql/epgsql/) seems to have support for `timeout`, but that doesn't appear to work either

**Comment by soedirgo** [comment]
So I just tried this while working on retendo's case, and it worked fine for me, though I'm using a `release` instead of `phx.server`.

I'll close this since it's an old issue, but feel free to reopen if the issue persists.
