### ISSUE TITLE
Use Server-Sent Event Notifications

### ISSUE THREAD

**Issue by vhscom** [supabase/realtime#244]
# Feature request
Add support for or switch to [Server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for notifications

## Is your feature request related to a problem? Please describe.

Web Sockets not necessary for unidirectional data flow.

## Describe the solution you'd like

Integration of SSE using standards-based approach.

## Describe alternatives you've considered

Using [Rocket.rs](https://rocket.rs/) to create a custom notifications endpoint.

## Additional context

I'd love to see SvelteKit support added as well, in addition to Next.js and Node. As a tangent.

**Comment by darora** [comment]
Is there a significant advantage that you're looking to pick up by using SSEs?

**Comment by vhscom** [comment]
Technically speaking I believe SSE would be ideal in a fire and forget realtime Notifications setting, which is the use case I'd like to achieve without taking on too much up-front technical debt:

- Unidirectional data flow (uses push model instead of requiring client to pull data)
- Uses standard HTTP protocol (easier to proxy, smaller up-front investment, less technical baggage)
- Reconnection handling is more robust from what I understand

There are some downsides depending on how you look at it:

- Limited to UTF-8 (so no binary data)
- Limited to six connections per browser

[Client adoption of SSE](https://caniuse.com/eventsource) is good at ~96% global adoption. And it can be polyfilled in older browsers, if necessary.

So what I'm proposing is a prototype for SSE, possibly using SvelteKit, to demonstrate a fire-and-forget notification API which uses `EventSource` and the bare minimum requirements (from a Web Standards perspective) to get it done. The benefit I see to Supabase is that it'll serve as a test for a realtime use case to ensure upstream changes aren't potentially breaking custom SSE implementations.

**Comment by w3b6x9** [comment]
@vhscom Thanks for the SSE feature request and for spelling out the pros + cons. We don't plan on introducing SSE to Realtime any time soon.

**Comment by vhscom** [comment]
Thanks for the follow-up. Probably better suited for a separate library. Thanks, Wen.

**Comment by w3b6x9** [comment]
@vhscom we will revisit SSE in the future and determine if it’s appropriate for Realtime.

Also, please call me Wen Bo!

**Comment by VittorioParagallo** [comment]
I was looking too for this feature. I used in some projects, and the idea to use SSE as Rest calls has several benefits.

**Comment by w3b6x9** [comment]
@VittorioParagallo thanks for your feedback! we will take it under advisement when we consider whether or not to add SSE.

**Comment by 0x-Legend** [comment]
Is the Broadcast using REST introduced in v2 pretty much SSE?

**Comment by rares-lupascu** [comment]
+1

**Comment by akash-giantanalytics** [comment]
Any update, guys? It's Sept 2025.

**Comment by funkeeflow** [comment]
Come on guys, its 2026 now, we need SSE :)

**Comment by filipecabaco** [comment]
Hi @funkeeflow , can you share some of the use cases and what would be the rare use cases?

**Comment by anthonycmain** [comment]
+1 for me too, I think it would be useful as there are a lot of chat libraries these days that have SSE functionality built in rather than having to plug in Supabase Realtime SDK
