### ISSUE TITLE
How can I paginate data with realtime api?

### ISSUE THREAD

**Issue by topperspal** [supabase/realtime#245]

**Comment by w3b6x9** [comment]
@topperspal Realtime doesn't support data pagination.

**Comment by kiwicopple** [comment]
Hey @topperspal - to set some more context here, you can request data using the API (https://supabase.com/docs/reference/javascript/select) and this supports pagination.

You can then subscribe to changes using Realtime.

These two combined should give you everything you need :). 

I'll close this for now, but if you have any questions feel free to drop a question in our Discussions here: 
https://github.com/supabase/supabase/discussions/categories/q-a

Thanks!
