### ISSUE TITLE
Cannot have multiple subscriptions on same table

### ISSUE THREAD

**Issue by leandertolksdorf** [supabase/realtime#246]
# Bug report

## Describe the bug

I have two independent React components from which I create supabase realtime subscriptions like this:

```
useEffect(() => {
  const subscription = supabase
    .from<definitions["customer"]>("customer")
    .on("*", () => console.log("change"))
    .subscribe();
  return () => supabase.removeSubscription(subscription);
});
```

When having both components in one page, one of the subscriptions doesn't fire on changing a row.

When changing the `"*"` in both components to differ from each other, for example

Component 1: `"INSERT"`
Component 2: `"UPDATE"`,

logging of `supabase.getSubscriptions()` shows that only one of them is present in `bindings`.

I assume the first loaded subscription is replaced with the second loaded when calling `subscribe()` again, and I'm not sure if this really is a bug or intended. 

## To Reproduce

1. Create two separate realtime subscriptions on the same table
2. After creating both, log `supabase.getSubscriptions()`. Only one will be present.
3. Have them both load on one page
4. Change anything in the DB and observe which subscription reacts to the change.

## Expected behavior

Both callbacks are run on DB change.

**Comment by WilliamFalci** [comment]
@leandertolksdorf before everything Im not a supabase mantainer or official dev... but I think maybe a lil bit more of code snapshot will help to understand where is the problem, personallly I used supabase realtime to make a multilevel customer helpdesk chat, but I did it with Vu3 + Vuex, where I have a class handle the chat and the costructor is stored into Vuex so every component can access to the proper data using the store's state.

Backing on topic the code you reported 
```
useEffect(() => {
  const subscription = supabase
    .from<definitions["customer"]>("customer")
    .on("*", query)
    .subscribe();
  return () => supabase.removeSubscription(subscription);
});
```
isn't the real code you applied, so it's hard understand where is the error and give to you a possible solution

**Comment by w3b6x9** [comment]
@leandertolksdorf We will consider allowing multiple subscriptions on the same table in the near future. For now, you'll just have to use a single subscription, get the changes, and then do some filtering client-side.

I'm going to close this issue b/c we intentionally enable a single subscription per table at the moment.

**Comment by Marviel** [comment]
@w3b6x9 Any idea where this sits on the future roadmap? It would be pretty useful from our perspective.

**Comment by Marviel** [comment]
@w3b6x9 By analogy, consider a Reddit-Like application, where most messages are public to all users.

If a user desired realtime updates on **only the messages that were currently visible**, it would be very excessive to subscribe to all messages on the entire platform.

Being able to subscribe to a single id is a start... but if there are multiple ids on the screen, this is insufficient, and we would need something like the [`in` query discussed here](https://github.com/supabase/walrus/issues/9#issuecomment-1018927685) to resolve this concern.

**Comment by Marviel** [comment]
UPDATE: Actually, it appears my understanding of the limitation here is inaccurate, based on this discussion post here: https://github.com/supabase/supabase/discussions/5684

It appears we can subscribe to multiple ids, because they are treated as separate subscription references.

**Comment by w3b6x9** [comment]
@Marviel yep, you can listen to as many unique ids as you want. The limitation here is that you can't listen to `foo_name:id=eq.7` twice using the same client.

Also, depending on one's use case they can also enable RLS and create the right policies so it's filtered automatically on the server so client can listen to just a schema or table and b/c of security client will only receive messages as specific by RLS policies.
