### ISSUE TITLE
Error 413: Payload Too Large

### ISSUE THREAD

**Issue by barbalex** [supabase/realtime#252]
# Bug report

## Describe the bug

I am subscribing to a table that contains files in a bytea field.
It seems that realtime does not like this as I get this error: `Error 413: Payload Too Large`

I am building an offline capable app that continually syncs data and files while online. So I need to know when a file was added.

I thought maybe I could get realtime to only send the id's of the changed datasets and then fetch the bytea columns with a regular query. But I have not found an option to choose what fields a payload contains.

What can I do?

## To Reproduce

Try to sync a table containing a bytea column that contains a file, in my case with 600KB.

## Expected behavior

Either: that syncing works for all fields, no matter what payload size is. 
Or: that I can choose what fields to include in the payload which enables fetching the large payload with a regular query.

Might be related to https://github.com/supabase/realtime/issues/119

**Comment by w3b6x9** [comment]
> I have not found an option to choose what fields a payload contains.

@barbalex Realtime currently does not support choosing the columns you want to include in the payload.

Let me see if there's a good way to pass the primary key when the error is 413 so that you can make a query for the data instead. I'll report back here soon.

**Comment by olirice** [comment]
@w3b6x9 here's the relevant source that filters out the `record` and `old_record`
https://github.com/supabase/walrus/blob/974798432bbb21d4838efa4ad3de2dd95f2b7edc/sql/walrus--0.1.sql#L455-L473

> Let me see if there's a good way to pass the primary key when the error is 413 

this risk in this case is that the primary key could be the one that includes the large amount of data e.g. a big string

What do you think about filtering out any columns that are > ~64 bytes.  That'll maintain guarantee we want about message size and will include the primary key columns unless the user sets the primary key as something crazy

**Comment by w3b6x9** [comment]
@barbalex we have now addressed this by way of my colleague @olirice's suggestion:

> What do you think about filtering out any columns that are > ~64 bytes. That'll maintain guarantee we want about message size and will include the primary key columns unless the user sets the primary key as something crazy

please give it a try and let me know what you think.
