### ISSUE TITLE
FunctionClauseError on event

### ISSUE THREAD

**Issue by orenwang** [supabase/realtime#255]
# Bug report

## Describe the bug

FunctionClauseError on Realtime server whenever there is an event, e.g. insert, and no event is received on subscribing clients. Note that **on v0.22.2 it is totally fine, but starting v0.22.3 this error appears every time.**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. sudo docker run -e DB_HOST='172.17.0.1' -e DB_NAME='postgres' -e DB_USER='postgres' -e DB_PASSWORD='PASSWORD' -e DB_PORT=5432 -e PORT=4000 -e JWT_SECRET='SECRET' -p 4000:4000 supabase/realtime
2. psql -U postgres
3. postgres=# CREATE TABLE distributors (
    postgres(#      did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    postgres(#      name   varchar(40) NOT NULL CHECK (name <> '')
    postgres(# );
4. postgres=# INSERT INTO distributors(did, name) VALUES (1, 'test');
5. See error.

## Expected behavior

Client should receive the INSERT event, and there should be no error on the Realtime server.

## Screenshots
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13847926/166127963-3376bf5e-98f5-4c58-93d6-a7e51e88eb24.png">

## System information

- OS: CentOS 8
- Version of supabase-py: 0.0.4

**Comment by w3b6x9** [comment]
@orenwang I believe you're self-hosting and running an older version of Realtime server that may be incompatible with `supabase-py: 0.0.4`. Can you please follow these instructions regarding Realtime RLS and try again? https://github.com/supabase/realtime#realtime-rls-database-setup

**Comment by orenwang** [comment]
Thanks for the response! @w3b6x9 

> I believe you're self-hosting...

Yes.
<br>

> running an older version of Realtime server...

The issue appears only in v0.22.3 and all later versions of Realtime server. As I stated, it is totally fine on older versions. Or do you mean Realtime is considered older than Realtime RLS? 
<br>

> may be incompatible with supabase-py: 0.0.4

I have tested against the latest @supabase/realtime-js. Same issue. Minimal js code below:
```javascript
const { RealtimeClient } = require('@supabase/realtime-js')

var client = new RealtimeClient("ws://43.134.91.139:4000/socket")
client.connect()
client.onError((e) => console.log('Socket error', e.message))

var databaseChanges = client.channel('realtime:*')
databaseChanges.on('*', (e) => console.log(e))
databaseChanges.subscribe()
```
<br>

> Can you please follow these instructions regarding Realtime RLS and try again?

Yep I will try this soon.

**Comment by orenwang** [comment]
So I tried to run RLS server but I couldn't get it work. After running `docker-compose -f docker-compose.rls.dev.yml up` everthing seems normal but no event is received on client... is there any more documentation on this? I must have missed some steps, like inserting a necessary policy/subcription?

**Comment by w3b6x9** [comment]
@orenwang can you please take a look at this checklist and make sure your local setup matches? https://github.com/supabase/supabase/issues/6290#issuecomment-1103424083

let me know if you're missing anything and i can continue to help you debug.

**Comment by w3b6x9** [comment]
@orenwang hey, just wanted to check in and see if you were able to get it to work.

**Comment by orenwang** [comment]
Hey @w3b6x9 , sorry for the late reply. Your checklist was SUPER helpful!

My issue with self-hosting Realtime RLS was that my JWT does not have a "role" field. After I add, it works perfect. Thx
