### ISSUE TITLE
How to get deleted rows since given date?

### ISSUE THREAD

**Issue by pie6k** [supabase/realtime#256]
Scenario:

Offline first app that keeps all available data persisted offline.

Use case:
User logs in and downloads all todos
There are 5 todos
User persists them locally 
Users goes offline for 5 hours 
During that time 1 of todos got removed (let's say Todo #3)
User goes back online
Question: how do I sync persisted local data to remove this 1 removed Todo without having to fetch all of them (it could be 5k instead of 5)?

Perfect flow would be:

Users gets back online
User asks realtime: what todos I have access to were removed (or I lost access to) since (5hours ago)
Server: Todo #3 
User: removes todo #3 from local data
User local data is in sync with remote data

**Comment by w3b6x9** [comment]
@pie6k Realtime does not persist the replicated database changes anywhere for playback. You will have to write custom logic and decide on where/how you wish to store this data and how you wish to query the data for a user that wants the last n hours worth of changes.

We have discussed internally building in similar functionality but do not plan on offering it any time soon.
