### ISSUE TITLE
Supabase realtime subscriptions are down/not working

### ISSUE THREAD

**Issue by pedrossdemelo** [supabase/realtime#268]
# Bug report

## Describe the bug

Supabase realtime subscriptions are down/not working

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a DB
2. Enable Realtime
3. Try to subscribe the UI to any changes

Example
```tsx
async function transactionPaper(cod: string, amount: number, sell: boolean) {
  const { error } = await supabase.from("transacoes").insert([
    {
      codAtivo: cod,
      qtdeAtivo: amount,
      venda: sell,
    },
  ]);

  if (error) {
    console.error(error);
  }
}

export default function usePaperTransaction(paper: Paper) {
  return {
    buyPaper: useCallback(
      (amount: number) => transactionPaper(paper.codAtivo, amount, false),
      [paper],
    ),
    sellPaper: useCallback(
      (amount: number) => transactionPaper(paper.codAtivo, amount, true),
      [paper],
    ),
  };
}

export function App() {
  const { buyPaper, sellPaper } = usePaperTransaction(Paper as any);

  React.useEffect(() => {
    const allSubs = supabase
      .from("*")
      .on("*", () => console.log("I'm working")) // Never gets called
      .subscribe();
    return () => {
      supabase.removeSubscription(allSubs);
    };
  }, []);

  return (
    <div>
      <button
        onClick={() => {
          console.log(supabase.getSubscriptions());
          // Shows the one subscription
          buyPaper(1);
        }}
      >
        Buy 1 AAPL
      </button>

      <button
        onClick={() => {
          console.log(supabase.getSubscriptions());
          // Shows the one subscription
          sellPaper(1);
        }}
      >
        Buy 1 AAPL
      </button>
    </div>
  );
}
```

## Expected behavior

For the websocket connection to listen to changes and update the ui

## System information

- macOS latest
- Chrome, Firefox
- Version of supabase-js: latest
- Node.js: 18.2

## Additional context

I've disabled RLS and also quadruple checked if all operations are being listened to on all tables

**Comment by w3b6x9** [comment]
@pedrossdemelo I looked at your projects and I saw that the migration that was mentioned in https://github.com/supabase/realtime/issues/265#issuecomment-1181560093 was already run successfully on both. Did you do anything else besides run that query to get Realtime working for you?

**Comment by w3b6x9** [comment]
@pedrossdemelo I'm going to close this issue but feel free to reopen should the same issue arise.

**Comment by pedrossdemelo** [comment]
> @pedrossdemelo I looked at your projects and I saw that the migration that was mentioned in https://github.com/supabase/realtime/issues/265#issuecomment-1181560093 was already run successfully on both. Did you do anything else besides run that query to get Realtime working for you?

You may have seen it before because I also opened a ticket on your website. The support staff may or may not have ran the same script before I ran it myself this morning. Anyways thanks for the awesome product!
