### ISSUE TITLE
Bulk updates "break" realtime

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime#269]
# Bug report

## Describe the bug
Was writing a quick test to check performance of realtime in the face of lots of database updates.

Doing an update of 5000 rows in a table (single SQL statement) works for 5000 rows (completes browser console logs in 1 second with or without RLS) to a single subscription (very impressive)

Doing an update of 7000 records returns only 5000 messages with no error.

Doing an update of 10000 records returns no messages and generates no error.

EDIT: adding a 2nd client computer does not impact the above, including 5000 records in about 1 second.

This is all on a free instance.  

I realize the test is not reflective of likely realworld apps, and realtime has warnings about overloading, but was looking into how fast realtime can generate payloads.

Is there any info or guidance on realistic bandwidth without failing silently?

## To Reproduce

Create a table with 10000 rows with an id column and a count column.
Use supabase.js to subscribe to the table.
In the SQL editor run 
UPDATE table SET count = count +1 WHERE id < 5000 (works) 
UPDATE table SET count = count +1 WHERE id < 10000 (does not work)

Edit:
This also works at 5000, fails at 10000.
```
 do $$
begin
for r in 1..5000 loop
insert into realtest(count) values(r);
end loop;
end;
$$;
```
## Expected behavior

Having better info on "breaking" points for realtime for various instance sizes.

## System information

Latest everything.

**Comment by chasers** [comment]
FYI ... we're internally doing load tests on Realtime v2 doing like 15,000 messages a second from database changes. 

> This is all on a free instance.

Sounds like this is on the hosted platform.  Since this test we've rolled out v2 on our side.  Can you run this again and see?

**Comment by chasers** [comment]
Actually ... this is probably more because of some rate limiting we're doing now on the Free plan since we have a shared cluster now with v2.

**Comment by GaryAustin1** [comment]
So the scenario I’m testing here is updating a user subscribe table where every user has a row.  Because of a lack of IN filter I need a way to handle a user subscribing to dozens of chat rooms but trying to avoid dozens of channels per user for each one.  So basically use a trigger when a message is updated to update the subscribe table with each user getting an update. 

I don’t see a problem for rooms with dozens to 100 or so users. But I have one room which is a status room and every user is a member.  So 10000 users will cause 10000 rows to update in a single trigger function.  This is a rare event and speed does not matter. But failure does.  Note the 10000 users are very likely not connected so real-time / replication is only stressed by the 10000 updates to a table very fast.  Of course 10000 is just a made up number and I assumed scaling the instance would solve it.

**Comment by GaryAustin1** [comment]
So running a test where I just use this sql: `update realtest set count = count +1  where id < 10000`
Works for up to 7500, fails silently at 10000.
I'm not likely to use this method, but failing without error (or realtime log if it is working as there are no log messages at all) is not good.

**Comment by chasers** [comment]
@GaryAustin1 This is handled now and you'll see a bunch of message per second rate limit errors in the Realtime logs.

It would be nice or Realtime to batch messages for you. #301 is a bit more reflective of this behavior so I'm going to close this and we can track there.
