### ISSUE TITLE
Cannot have multiple subscriptions on same table

### ISSUE THREAD

**Issue by leandertolksdorf** [supabase/realtime#271]
NOTE: This is a duplicate of https://github.com/supabase/realtime/issues/246 because I'm not sure to which repository this actually belongs.

# Bug report

## Describe the bug

I have two independent React components from which I create supabase realtime subscriptions like this:

```
useEffect(() => {
  const subscription = supabase
    .from<definitions["customer"]>("customer")
    .on("*", () => console.log("change"))
    .subscribe();
  return () => supabase.removeSubscription(subscription);
});
```

When having both components in one page, one of the subscriptions doesn't fire on changing a row.

When changing the `"*"` in both components to differ from each other, for example

Component 1: `"INSERT"`
Component 2: `"UPDATE"`,

logging of `supabase.getSubscriptions()` shows that only one of them is present in `bindings`.

I assume the first loaded subscription is replaced with the second loaded when calling `subscribe()` again, and I'm not sure if this really is a bug or intended. 

## To Reproduce

1. Create two separate realtime subscriptions on the same table
2. After creating both, log `supabase.getSubscriptions()`. Only one will be present.
3. Have them both load on one page
4. Change anything in the DB and observe which subscription reacts to the change.

## Expected behavior

Both callbacks are run on DB change.

**Comment by w3b6x9** [comment]
@leandertolksdorf this is intended. When you do `.on("*")` you're essentially listening to the following topic `realtime:*`. Currently, Realtime only allows listening to unique topics per socket connection.
