### ISSUE TITLE
Error when trying to update the auth token

### ISSUE THREAD

**Issue by jan-tennert** [supabase/realtime#272]
# Bug report

## Describe the bug

I'm currently writing an realtime client for kotlin and everything works so far but I'm having one small problem with updating the auth token.
I'm not even sure if this is a bug, or I'm just dumb, but if I try to send the packet to update the auth token for a subscription, I'm getting this error:

```json
{"event":"phx_error","payload":{},"ref":null,"topic":"topic"}
```

## To Reproduce

- connect to the realtime websocket
- subscribe to a topic
- update the auth token with this packet:
```json
{
  "topic": "topic",
  "event": "access_token",
  "payload": {
    "access_token": "token"
  },
  "ref": "2"
}
```
-> I'm getting the error above as response (and of course no events anymore, as the packet is normally sent when the auth token has expired)

## Expected behavior

You get a normal reply with an "ok"

## Additional context

I'm using supabase.com for the hosting. Also, before trying to update the auth token everything works normally, and I'm receiving events for the topic

**Comment by w3b6x9** [comment]
@jan-tennert just confirming that your topic is actually `realtime:topic` (starts with `realtime:`) when you run it. can you please create a ticket over at https://app.supabase.com/support/new with your Supabase project ref and I can take a look?

**Comment by jan-tennert** [comment]
sure

**Comment by jan-tennert** [comment]
Also my topic is **test** was just generalizing the bug. As said, I'm receiving database updates normally but I can't update the auth token

**Comment by w3b6x9** [comment]
@jan-tennert feel free to reopen this if the issue comes up again.

**Comment by jan-tennert** [comment]
The issue fixed itself somehow no idea what was causing it
