### ISSUE TITLE
Realtime stopped working while migrating to the `0.24.0` docker image

### ISSUE THREAD

**Issue by bhvngt** [supabase/realtime#284]
# Bug report

## Describe the bug

While migrating to the latest realtime [image](https://hub.docker.com/layers/realtime/supabase/realtime/latest/images/sha256-99a3a3f397495141648c3f999eb9e26f4f6ecd21e1cbad9b33a0a3333a2f0589?context=explore) from `realtime/walrus` image, realtime has stopped working. In the docker logs its giving following errors

```
realtime-realtime-1  | 2022-08-23 09:20:02.744 [info] REFUSED JOIN realtime:public:users in 165µs
realtime-realtime-1  |   Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "INSERT", "schema" => "public", "table" => "users"}], "presence" => %{"key" => ""}}}
```

## To Reproduce

I have cloned this repo and made following changes to migrate to `supabase-js` `v2`.

1. changed docker realtime image inside `docker-compose.rls.dev.yml` from `realtime/walrus` to `supabase/realtime:latest`.
2. Upgraded `@supabase/realtime-js` from `^1.7.2` to `^2.0.0-rc.5`.
3. Ran following js code using node cli

```
const {RealtimeClient} = require('@supabase/realtime-js')

const REALTIME_URL = process.env.REALTIME_URL || 'http://localhost:4000/socket'
const JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNDQ0MzksInJvbGUiOiJhdXRoZW50aWNhdGVkIn0.I8eSzCD7YjwsYPQE77PSxqaS-I107zHybTsP5TQgNiM";
const socket = new RealtimeClient(REALTIME_URL, {
    params: {apikey: JWT}
});
socket.connect();
const subscribe = socket.channel('public:users')
  .on('postgres_changes', {event: "INSERT", schema: "public", table: "users"}, (change) => {
      console.log('Change received on public.users', change)
  }).subscribe();

console.log(`subscribe.state`, subscribe.state);
```
4. Executed few inserts into `public.users` table.

CLI only display `subscribe.state joining` and then does not display any realtime database changes. Whereas docker logs display following error message.

```
 2022-08-23 09:20:02.744 [info] REFUSED JOIN realtime:public:users in 165µs
realtime-realtime-1  |   Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "INSERT", "schema" => "public", "table" => "users"}], "presence" => %{"key" => ""}}}
``` 

When I change the image back to `realtime/walrus` everything starts working out fine.

## Expected behavior

I was expecting realtime feed of inserted user table records with the `supabase/realtime:latest` image.

## System information

- OS: macOS
- Version of @supabase/realtime-js: `2.0.0-rc.5`
- Version of docker image: `supabase/realtime:latest`
- Version of Node.js: `18.7.0`

## Additional context

Here's the relevant docker realtime image log

```
realtime-realtime-1  | 2022-08-23 09:19:52.941 [info] == Migrated 20220615214548 in 0.0s
realtime-realtime-1  | 2022-08-23 09:19:52.944 [info] == Running 20220712093339 Realtime.RLS.Repo.Migrations.RecreateRealtimeBuildPreparedStatementSqlFunction.change/0 forward
realtime-realtime-1  | 2022-08-23 09:19:52.944 [info] execute "\n      create or replace function realtime.build_prepared_statement_sql(\n          prepared_statement_name text,\n          entity regclass,\n          columns realtime.wal_column[]\n      )\n          returns text\n          language sql\n      as $$\n      /*\n      Builds a sql string that, if executed, creates a prepared statement to\n      tests retrive a row from *entity* by its primary key columns.\n      Example\n          select realtime.build_prepared_statement_sql('public.notes', '{\"id\"}'::text[], '{\"bigint\"}'::text[])\n      */\n          select\n      'prepare ' || prepared_statement_name || ' as\n          select\n              exists(\n                  select\n                      1\n                  from\n                      ' || entity || '\n                  where\n                      ' || string_agg(quote_ident(pkc.name) || '=' || quote_nullable(pkc.value #>> '{}') , ' and ') || '\n              )'\n          from\n              unnest(columns) pkc\n          where\n              pkc.is_pkey\n          group by\n              entity\n      $$;\n    "
realtime-realtime-1  | 2022-08-23 09:19:52.946 [info] == Migrated 20220712093339 in 0.0s
realtime-realtime-1  | 2022-08-23 09:19:56.381 [info] Running RealtimeWeb.Endpoint with cowboy 2.8.0 at :::4000 (http)
realtime-realtime-1  | 2022-08-23 09:19:56.382 [info] Access RealtimeWeb.Endpoint at http://localhost:4000
realtime-realtime-1  | 2022-08-23 09:19:56.746 [info] CONNECTED TO RealtimeWeb.UserSocket in 185µs
realtime-realtime-1  |   Transport: :websocket
realtime-realtime-1  |   Serializer: Phoenix.Socket.V1.JSONSerializer
realtime-realtime-1  |   Parameters: %{"apikey" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjEyNDQ0MzksInJvbGUiOiJhdXRoZW50aWNhdGVkIn0.I8eSzCD7YjwsYPQE77PSxqaS-I107zHybTsP5TQgNiM", "vsn" => "1.0.0"}
realtime-realtime-1  | 2022-08-23 09:19:56.755 [info] REFUSED JOIN realtime:public:users in 95µs
realtime-realtime-1  |   Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "INSERT", "schema" => "public", "table" => "users"}], "presence" => %{"key" => ""}}}
```

**Comment by w3b6x9** [comment]
@bhvngt can you please try it with @supabase/realtime-js v1.7.4?

`supabase/realtime` docker image is not yet compatible with @supabase/realtime-js rc versions. We've been developing the new Broadcast and Presence in a private repo and will be moving over all code to this repo in the upcoming weeks.

**Comment by bhvngt** [comment]
Ohh. Ok.. sure.

**Comment by w3b6x9** [comment]
@bhvngt feel free to reopen if you're still having issues.

**Comment by bhvngt** [comment]
@w3b6x9 I am getting duplicate feed transmission with the [latest](https://hub.docker.com/layers/realtime/supabase/realtime/latest/images/sha256-99a3a3f397495141648c3f999eb9e26f4f6ecd21e1cbad9b33a0a3333a2f0589?context=explore) docker image. So every table insert, I see two records in the realtime feed.

Here's the code that I am running in the browser

```javascript
const anonKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyNzIwODU0MCwiZXhwIjoxOTc0MzYzNzQwfQ.zcaQfHd3VA7XgJmdGfmV86OLVJT9s2MTmSy-e69BpUY";
let supabaseUrl = "http://localhost:4000";
supabase = createClient(supabaseUrl, anonKey);
await supabase.auth.signOut();
await supabase.auth.signInWithPassword({email: "test@example.app", password: "WNdn+aR_G-D6uHFF"});
supabase.channel("public:test_tbl").on("postgres_changes", {
	event: "INSERT",
	schema: "public",
	table: "test_tbl"
}, (payload:any) => {
	console.log(payload)
}).subscribe();
``` 

When I switch my docker image to [v0.22.7](https://hub.docker.com/layers/realtime/supabase/realtime/v0.22.7/images/sha256-a96ddfa6b7e95334b22c1bab04df7d22a5bcd98c1ac0ab265616765019df9fc7?context=explore) it works fine i.e. I don't see any duplicates.

docker realtime container logs appears to be similar.

**Comment by bhvngt** [comment]
Guess my issue is a duplicate of #287.

**Comment by w3b6x9** [comment]
@bhvngt fixed! see: https://github.com/supabase/realtime/issues/287#issuecomment-1232283060

**Comment by agubler** [comment]
Hi @bhvngt, using the latest released client (`1.11.2`) that has been updated to use `"supabase/realtime:v0.25.1"` docker image, I am receiving similar errors locally when trying to subscribe to a postgres channel - Is there anything I need to do get the latest cli to work locally?

```
2022-10-26 14:24:29.266 [info] REFUSED JOIN realtime:public:mytable:id=eq.958f3280-5539-11ed-82aa-7d0dc1b51751 in 854µs
  Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "UPDATE", "schema" => "public", "table" => "mytable"}], "presence" => %{"key" => ""}}}
```

The same code works locally using version `1.8.7` of the cli that uses `"supabase/realtime:v0.22.7"`. Any assistance would be greatly appreciated!

**Comment by bhvngt** [comment]
@agubler I am using [v0.24.2](https://hub.docker.com/layers/supabase/realtime/v0.24.2/images/sha256-ea51a8027b33da928deeeadf650d1968ce7d1e21f818b3886788e0ae615731dd?context=explore). With following `docker-compose` config and code, I am able to subscribe to the realtime channel.

```docker-compose.yaml
  realtime:
    container_name: supabase-realtime
    image: supabase/realtime:v0.24.2
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${PGDATABASE}
      DB_USER: ${PGUSER}
      DB_PASSWORD: ${PGPASSWORD}
      DB_SSL: "false"
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET}
      REPLICATION_MODE: RLS
      REPLICATION_POLL_INTERVAL: 100
      SECURE_CHANNELS: "true"
      SLOT_NAME: supabase_realtime_rls
      TEMPORARY_SLOT: "true"
    command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"
```

```typescript
    const subscription = this.connection.client
                             .channel(`public:${tableName}`)
                             .on("postgres_changes", { event: "*", schema: "public", table: ${tableName} }, (payload: any) => console.log(payload))
                             .subscribe((event: string) => console.log(event));
```

Typically, I have received `REFUSED JOIN` error when I had missed passing `api` key to my supabase connection. You may want to check that. I am assuming hat your table has already been added to `supabase_realtime` publication. 

It will help to see your code snippet and docker config. 

I haven't tried with [v0.25.1]([v0.25.1](https://hub.docker.com/layers/supabase/realtime/v0.25.1/images/sha256-7fc3731782f80e1f5e8b375bce0ebb223229690da1b73997e44dbb31a16fe885?context=explore)), Also noticed that they have released `v1.0.0-rc.2`. This may be supporting `presence` and `broadcast` features. These were not supported in the docker images.

**Comment by agubler** [comment]
Thanks for getting back to me @bhvngt, I am not using docker compose directly I am using `supabase start` from the CLI but this is the subscription I have been using which works with version `1.8.7` of the CLI (which uses `v0.22.7` of realtime under the hood)

```ts
const channelName = `public:game:game_id=eq.${state.gameId}`;
const channelEvent = { event: 'UPDATE', schema: 'public', table: 'game' } as const;
const ids = data.actions.map(({ correlationId }: any) => correlationId);

client.channel(`public:game:game_id=eq.${state.gameId}`)
	.on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'game' } , (payload) => {
		console.log((payload as any).record || payload.new);
	})
	.subscribe();
```

Yes the table is added to the `supabase_realtime` publication, using `alter publication supabase_realtime add table game;` in the migration.

**Comment by bhvngt** [comment]
hmm.. I have not been using `supabase cli` since I like the flexibility `docker-compose` provides. However, I do loose out on some of the functionalities that `supabase-cli` provides.

I tried my setup with `v0.25.1` and it is working fine without any issue. However, `v1.0.0-rc.1` and `v1.0.0-rc.2` are giving me trouble with following log - `./prod/rel/realtime/bin/realtime: No such file or directory`. That may be a different issue though.

How are you initiating the `supabase` connection?

**Comment by bhvngt** [comment]
Do you get similar error if you subscribe to `public:game` channel with event as `*`.

**Comment by bhvngt** [comment]
I am not too sure why it is not working out for you. I have been using it with RLS and have been initiating my connection with following code snippet

```typescript
const supabase = createClient(SUPABASE_URL, ${anonKey}, {global: {headers: {Authotization: `Bearer ${authToken}`}}});
```

You may want to raise this as a new issue!! It might have something to do with `supabase-cli`.

**Comment by agubler** [comment]
@bhvngt thanks for your help, I've setup a small repro of my issue that demos the same code working with the older version of the supabase cli and realtime docker image but not working with the latest

https://github.com/agubler/supabase-realtime-repro

I hope this is helpful and please let me know if you want me to raise as a new issue against either the cli or realtime repository.

**Comment by bhvngt** [comment]
Since the issue seems to be unrelated to the current thread. It is best to create a new issue and ping the supabase team member @w3b6x9 for additional help.
