### ISSUE TITLE
Receive duplicated messages using v0.24.1 image

### ISSUE THREAD

**Issue by mats16** [supabase/realtime#287]
# Bug report

## Describe the bug

Use v0.24.1 docker image, I receive duplicated messages from realtime API.

## To Reproduce

Use v0.24.1 docker image

## Expected behavior

Receive one message.

## System information

- Version of supabase-realtime: v0.24.1

**Comment by mats16** [comment]
It works correctly using v0.24.0 .

**Comment by w3b6x9** [comment]
@mats16 thanks for reporting! Are you seeing duplicate messages in the log or when you use a client lib? I'll investigate and put in a fix very soon.

**Comment by bhvngt** [comment]
@w3b6x9 I am getting duplicate message in the realtime feed.

**Comment by mats16** [comment]
I had test with this demo - https://github.com/shwosner/realtime-chat-supabase-react .

I have also checked with browser developer tools and received the same message at the same time.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5158858/187542111-3800b9cd-4df8-494c-b528-20d3f7343810.png">

**Comment by w3b6x9** [comment]
@mats16 sorry about that! this is fixed in [v0.24.2](https://github.com/supabase/realtime/releases/tag/v0.24.2).

**Comment by mats16** [comment]
Cool!
