### ISSUE TITLE
Random `SLOT_NAME` support

### ISSUE THREAD

**Issue by mats16** [supabase/realtime#289]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to set a random value for SLOT_NAME instead of a fixed parameter. It is needed with auto scaling.

e.g. HOSTNAME

## Describe the solution you'd like

Add option to set other environment variables to SLOT_NAME or set random value.

## Describe alternatives you've considered

Containers have a random host name, so I think it is appropriate to use that.

**Comment by mats16** [comment]
Sorry.
I run Realtime server with k8s or Amazon ECS and these services run some containers with common configuration.
It means some containers have same `SLOT_NAME` within environment variable.

This is very inconvenient to run multiple containers as Realtime server.

**Comment by mats16** [comment]
Sorry @chasers .
I run Realtime server with k8s or Amazon ECS and these services run some containers with common configuration.
It means some containers have same `SLOT_NAME` within environment variable.

This is very inconvenient to run multiple containers as Realtime server.

**Comment by chasers** [comment]
In progress!! #368

**Comment by chasers** [comment]
[Done!](https://github.com/supabase/realtime/blob/36c8a4b6a93e6e7eddc2acd20b1cb141bf352757/README.md#L151)
