### ISSUE TITLE
postgres_changes subscription does not trigger locally

### ISSUE THREAD

**Issue by jonmumm** [supabase/realtime#290]
# Bug report
The docs show a way to subscribe to postgres changes here: https://supabase.com/docs/guides/realtime/postgres-changes. This works against the hosted supabase service, but it does not work locally.

## Describe the bug

Setting up a postgres change listener works against hosted supabase, but not locally.

## To Reproduce
```typescript
        supabaseClient
          .channel('db-changes')
          .on(
            'postgres_changes',
            { event: 'INSERT', schema: 'public', table: 'parties' },
            (payload: unknown) => {
              console.log('new party', payload); // never logged locally
            }
          )
          .subscribe();
```

## Additional context

It seems to be related to the supabase cli runing realtime version `0.22.7` but support for this API was introduced in `0.24.0`.

https://github.com/supabase/cli/blob/826409f97ddba8514d025fea1a9d0046423c9349/internal/utils/misc.go#L39

https://github.com/supabase/realtime/commit/9f0b1d1c90a67aa3f9ac19039c3df4b933dd042f

**Comment by elmarquez** [comment]
+1 this is a blocker for me. Is there an approach for manually updating the dependency?

**Comment by w3b6x9** [comment]
@jonmumm @elmarquez please take a look at this comment: https://github.com/supabase/realtime/issues/284#issuecomment-1224908325.
