### ISSUE TITLE
404 on websocket for projects being restarted from pause and older projects being upgraded.

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/realtime#296]
# Bug report

At least two Discord users were having 404 errors to the realtime websocket on projects that changed status yesterday.

One was a paid plan project that was upgraded yesterday.  Support fixed this issue. https://discord.com/channels/839993398554656828/1023386785746780262

Another one today was a 3 month paused instance, restored yesterday.  The OP chose to generate a new instance which fixed the problem.  https://discord.com/channels/839993398554656828/1023710779372998747  This one in particular is concerning because they just happened to be adding realtime to their app today, but could have been weeks from now.

## To Reproduce

I see two possibilities. 
1) Instances restored or upgraded yesterday are not setup properly for realtime.
2) "Older" instances being restored or upgraded currently are not setup properly.  

I can't test either, but did test pausing and restoring a currently running instance with no issue today helping the 2nd user.

## Expected behavior

Realtime should setup properly for the new configuration when projects are restored.
Hopefully this issue will help anyone going thru the same thing, or down the road if they restored a project with this bad condition and add realtime features later.

## System information

Hosted Supabase instances.

**Comment by chasers** [comment]
Hey @GaryAustin1 yeah we'll dig into this.

**Comment by chasers** [comment]
Okay I think we actually fixed this today, please re-open if you see it again.

**Comment by w3b6x9** [comment]
> Instances restored or upgraded yesterday are not setup properly for realtime.

@GaryAustin1 this could be the culprit as I just moved over remaining unpaused projects that were not using the correct Realtime. All future unpaused projects will be on the correct Realtime so if this happens again then we can rule this out.

**Comment by GaryAustin1** [comment]
If I understand correctly then for some number of projects that were unpaused over a short time period realtime will not work.  Those users may find out quickly if they are using realtime, or they may find out weeks from now if they start using realtime.  Hopefully that number is few and they ask for help or search here before wasting a bunch of time.
