### ISSUE TITLE
User-defined columns in CamelCase stop realtime from sending updates

### ISSUE THREAD

**Issue by NiklasPor** [supabase/realtime#306]
# Bug report
User-defined columns in **C**amel**C**ase stop realtime from sending updates to the client. 

- Related bug from the past: supabase/realtime#211
- Related [discord discussion](https://discord.com/channels/839993398554656828/1031895957694054491)
- Only happens on remote environments, not if you're using the CLI / docker environment

## Describe the bug

When a table contains a user-defined field with **C**amel**C**ase naming, realtime stops sending updates for the table.

## To Reproduce

```sql
CREATE TYPE "public"."ProjectStatus" AS ENUM (
    'Available',
    'Archived',
    'Deleted'
);

CREATE TABLE "public"."Project" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "name" character varying NOT NULL,
    "status" "public"."ProjectStatus" DEFAULT 'Available'::"public"."ProjectStatus" NOT NULL
);
```

```ts
  supabase
    .channel('*')
    .on('postgres_changes', { event: '*', schema: '*' }, (payload) => console.log(payload))
    .subscribe();
```

Result:
- Logs don't show anything
- WebSocket inspector is also not showing anything

## Workaround

Renaming the types to snake_case fixes the problem and supabase sends updates again:
```sql
ALTER TYPE public."EntityStatus" RENAME TO entity_status;
```

## System information

- OS: macOS
- Supabase CLI: 1.8.7 (bug is not occuring there, only on remote)
- supabase-js: 2.0.0

## Additional context

As stated at the beginning, a very similar / same bug already appeared in the past: supabase/realtime#211

**Comment by w3b6x9** [comment]
@NiklasPor we have just deployed a fix so this shouldn't be an issue anymore.

**Comment by NiklasPor** [comment]
Wow, thanks a lot!
