### ISSUE TITLE
Subscribing to PostgreSQL failed: {:error, :malformed_subscription_params}

### ISSUE THREAD

**Issue by CodyBontecou** [supabase/realtime#307]
# Bug report

## Describe the bug

Subscriptions were working up until about two hours ago. I am now seeing the following error in my real-time logs: 
`Subscribing to PostgreSQL failed: {:error, :malformed_subscription_params}`

## Expected behavior

I should be seeing real-time subscriptions occurring.

## Screenshots
<img width="1414" alt="Screen Shot 2022-10-22 at 1 40 47 PM" src="https://user-images.githubusercontent.com/20440899/197366311-b3a61e35-50d5-4640-a6d9-daa07677868a.png">

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: "@nuxtjs/supabase": "^0.1.27" (I've also tried "@nuxtjs/supabase": "^0.2.00")
- Version of Node.js: v16.14.2

**Comment by CodyBontecou** [comment]
A few hours later, I still see the error message within my logs, but I can now see the subscription payload in the client.

**Comment by w3b6x9** [comment]
@CodyBontecou can you share your Realtime setup?
