### ISSUE TITLE
Unable to locally subscribe to a postgres table with the latest version of supabase realtime and cli

### ISSUE THREAD

**Issue by agubler** [supabase/realtime#309]
# Bug report

When running locally I am unable to connect to a postgres CDC subscription with the latest version of the supabase:realtime docker image (`0.25.1`) using the latest supabase cli (`1.11.2`).

```
2022-10-27 08:59:13.902 [info] CONNECTED TO RealtimeWeb.UserSocket in 225µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V1.JSONSerializer
  Parameters: %{"apikey" => "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs", "vsn" => "1.0.0"}
2022-10-27 08:59:13.906 [info] REFUSED JOIN realtime:public:example in 164µs
  Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "INSERT", "schema" => "public", "table" => "example"}], "presence" => %{"key" => ""}}}
```

The same implementation worked fine with supabase:realtime docker image (`0.22.7`) using the latest supabase cli (`1.8.7`)

## To Reproduce

I've created a github repository that demonstrates the issue with the latest cli/realtime versions and working with the previous versions.

https://github.com/agubler/supabase-realtime-repro

Instructions are in the README.md

## Expected behavior

Expects the example to successfully connect to the subscription and receives updates.

## Screenshots

N/A

## System information

- OS: Mac Montery (12.6)
- Browser: Chrome latest
- Version of supabase-js: https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.0.4/+esm
- Version of Node.js: v16.15.1

## Additional context

I am not sure if this is an issue with the realtime version of the latest cli, please feel free to move the issue to the cli if it is a more appropriate place.

**Comment by agubler** [comment]
Hi @w3b6x9, I was told to ping you about my issue realtime/cli issues 😄

**Comment by jstdk** [comment]
I have the same issue on my https://github.com/jstdk/starter repo. Realtime works online, but does not work locally. I use the supabase-flutter package.

**Comment by xxRockOnxx** [comment]
Thanks for the hint that it works on latest version of supabase/realtime.
I upgraded the CLI and it worked. However there seems to be an issue still on certain tables?
Related: https://github.com/supabase/supabase/issues/9798

It'd throw an error of

> CHANNEL_ERROR Error: "error occurred when joining realtime:public:<table-name>"

**Comment by w3b6x9** [comment]
The problem here is that `supabase/realtime` docker image v0.25.1, or any earlier version, is not yet compatible with `supabase-js` v2.

We recently released `supabase/realtime` [v1.0.0-rc.1](https://hub.docker.com/layers/supabase/realtime/v1.0.0-rc.1/images/sha256-174b7e53bfa5cd0806ae7cd93b241a0e257a158b078cd4dd5baef30aae12290d) which will work with `supabase-js` v2.

However, we'll need to update a lot of the set up in order for everything to work.

I'll try and tackle this some time this week and update the `cli`.

**Comment by jchekanoff** [comment]
@w3b6x9 thanks for the update! just a +1 for this issue affecting our ability to work locally. looking forward to seeing the update live in the `cli`.

**Comment by WesleyYue** [comment]
> The problem here is that `supabase/realtime` docker image v0.25.1, or any earlier version, is not yet compatible with `supabase-js` v2.
> 
> We recently released `supabase/realtime` [v1.0.0-rc.1](https://hub.docker.com/layers/supabase/realtime/v1.0.0-rc.1/images/sha256-174b7e53bfa5cd0806ae7cd93b241a0e257a158b078cd4dd5baef30aae12290d) which will work with `supabase-js` v2.
> 
> However, we'll need to update a lot of the set up in order for everything to work.
> 
> I'll try and tackle this some time this week and update the `cli`.

Any reason why this isn't in the docs? Would have saved me a ton of time. In general it feels like the docs are insanely sparse for a production developer infra product.

**Comment by 413n** [comment]
+1

**Comment by w3b6x9** [comment]
I've pinned this issue and I opened up a draft PR where you can track development: https://github.com/supabase/cli/pull/594.

There's two blockers that I'm trying to work through with the team right now and will provide updates as I work through them.

**Comment by w3b6x9** [comment]
This has been resolved! Just update your Supabase CLI to the latest version and you should be good to go.
