### ISSUE TITLE
Landing page updates: Phoenix Dashboard

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#32]
When you start the server, there is just a page that says: "visit supabase.io"

We can do better than that. I recommend with either do one/both of:

1. A page describing what this server is, the URL and the port to access it on
2. Phoenix dashboard: https://github.com/phoenixframework/phoenix_live_dashboard

**Comment by soedirgo** [comment]
We probably don't need this right now, we can revisit landing page in the future.
