### ISSUE TITLE
Refactor the notifiers logic and plan for connectors

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#33]
At the moment our decoder gen_server is doing a lot of work. We should (maybe) refactor it into smaller gen_servers, specifically this part here:

https://github.com/supabase/realtime/blob/1d7cf1162eb40e5f3c6c9349e2509cd7f7f8914c/server/lib/realtime/replication.ex#L202

This part is where we parse the data changes and then send it to various channel topics:

![image](https://user-images.githubusercontent.com/10214025/82281557-3597c500-99c4-11ea-9acb-6b17b71a244f.png)

It will be better to separate this out. because we eventually want this structure (comments/improvements:

![image](https://user-images.githubusercontent.com/10214025/82281824-e9995000-99c4-11ea-902e-0c8d0d4629bf.png)

**Comment by fracek** [comment]
I think this one was fixed by #36. You can add connectors by adding a new genserver and notify it from the replication genserver.

**Comment by kiwicopple** [comment]
Great - remaining questions:

- let's say I create a genserver called "connectors" which stores all the different locations that a customer wants to send the events too
- I create a genserver called "webhook" which will POST the event to a URL

As a customer, I want to start the server and have it send the events to 2 endpoints:

- https://webhook.site/44e4457a-77ae-4758-8d52-17efdf484853
- https://webhook.site/c451c09e-6363-45fe-aeff-9cf577681058

How would I pass those to the server? Env vars don't seem like a good way, as it needs to be an array (and other connectors might need additional config).

Ideas:

- Maybe some sort of JSON file that the "connectors" genserver can read from? To update the sources/connectors we can then just restart the "connectors" genserver which will read the file again?

**Comment by fracek** [comment]
One option is to use config providers in `releases.exs` and add a [provider](https://hexdocs.pm/elixir/Config.Provider.html) for the configuration.

Another (and IMHO better) option is to use an agent to hold the configuration. At the beginnig you can keep it simple (simply read from a json configuration file), but can be easily improved by adding configuration through HTTP endpoints/consul etc. The important thing is that all processes read the configuration from the agent and subscribe to be notified when the configuration changes so that the data they need.

**Comment by fracek** [comment]
Can you expand more on how you plan to allow customers to configure the service from the dashboard? How will this configuration be accessible by realtime? (http, direct db access, etc.) I'm trying to think of a design that's easy to setup but that can also be expanded in the future to let customers load the configuration from multiple sources.

**Comment by kiwicopple** [comment]
I'll put this one on Slack with a video

**Comment by fracek** [comment]
So I tought more about this and if the configuration resides outside the process (e.g. json file, supabase server) there is no need for an agent. We would have a `ConfigurationManager` whose repsonsibility is to fetch the configuration and parse it into elixir types.

Then I add a `Connectors` genserver that simply forwards notifications to other connectors (for now only webhooks). The `Webhooks` genserver looks up endpoints by the notification payload and class them in a separate Task. 

I sketched the genservers and messages below, rectangles are genservers and arrows are messages. In green what we have, in black what needs to be added for this issue, in grey what can be added in the future.

![Untitled-2020-04-21-1617 (2)](https://user-images.githubusercontent.com/282580/82727593-583b1e00-9ce3-11ea-8b3a-cbff667d910a.png)

In the future you can swap the configuration manager with something more complex (and configurable), for now it will load the configuration from json.

**Comment by kiwicopple** [comment]
This looks perfect with perhaps one missing piece: the `SubscribersNotification` genserver that you just split out. At the moment that sits between `Replication` and `Channels`. 

The `Connectors` genserver needs to also "pull apart" the events into many different events (eg: `*`, `INSERT`, `columns.eq...`). We have 2 options:

1. the `SubscribersNotification` genserver could also send everything to `Connectors` which would then match against all events in `Config Manager` 
2. the `Connectors` directly receives the changes, fetches the config from `Config Manager` and then see if the `Replication` event matches any of the config

Preference is `1` (less to maintain) unless you have any opinions on how you think it might fit together

**Comment by fracek** [comment]
Agree with option 1, so the final design for now is like this.

![Untitled-2020-04-21-1617 (3)](https://user-images.githubusercontent.com/282580/82730706-afe48400-9cf9-11ea-8cad-7cac6b6f7204.png)

Connectors job is to dispatch messages to the right connector based on the event type.

**Comment by kiwicopple** [comment]
Looks perfect 👍 

Love the diagrams

**Comment by fracek** [comment]
I made progress on this. A couple of questions before I can open a PR:

 * I added a filter by event type and schema/relation, but not on column value (I think it needs a separate discussion for it).
 * In the configuration, I added what we need for the connectors. Basically it loads the json configuration and parse it into a nice datastructure we can work with. This is kinda related to #31, but I think it's important to distinguish between static configuration properties (port, db connection) and dynamic ones (webhooks, connectors).
 * I'm using HTTPoison to make the call to the webhooks, let me know if you want me to use a different library.
 * What should happen if a webhook returns a status code that's not `2xx`? At the moment I log a warning.

**Comment by kiwicopple** [comment]
Nice Francesco

> I'm using HTTPoison

👍 

> What should happen if a webhook returns a status code that's not 2xx? At the moment I log a warning.

I think that's good - we can send all the logs to BigQuery and set up alerts for the user.

> I think it's important to distinguish between static configuration properties

Agreed 

>  I added a filter by event type and schema/relation, but not on column value (I think it needs a separate discussion for it).

It's one I wanted to discuss more too. At the moment we are only filtering on equality. It would be good to throw around some ideas how we can do more/better. Let's discuss on slack or in a new issue

**Comment by fracek** [comment]
> It's one I wanted to discuss more too. At the moment we are only filtering on equality. It would be good to throw around some ideas how we can do more/better. Let's discuss on slack or in a new issue

We can discuss it in a separate issue. For now I will stub the transaction filter module with just the basics.

**Comment by kiwicopple** [comment]
This change is amazing, thanks @fracek. It opens up a number of new possibilities.

It looks like we have 2 remaining points to discuss

- the transaction filter module
- a way to dynamically update/create the connectors config

Should we spin off separate issues for those?

**Comment by fracek** [comment]
I think they're both issues important enough to require their own issue.

**Comment by kiwicopple** [comment]
Great - I imagine you already have some ideas for them both? Do you want to start the issues and add your thoughts?

I'll close the one
