### ISSUE TITLE
Support hypertables

### ISSUE THREAD

**Issue by jsbrain** [supabase/realtime#333]
# Feature request

I have a timescale hypertable that looks like this:

```sql
create table
  public.measures (
    time timestamptz not null,
    id text not null,
    value text not null,
    primary key (id, time)
  );

select extensions.create_hypertable ('public.measures', 'time', migrate_data => true);
```

Now I noticed, that I cannot subscribe to the table to use realtime events. Well actually I can subscribe but there won't be any events.

I found out, that I can work around this by subscribing to the hypertable chunk directly, e.g. instead of

```ts
const channelId = `public:measures`;
const channel = supabaseClient
  .channel(channelId).on(
    'postgres_changes',
    {
      schema: 'public',
      event: 'UPDATE',
    },
    (payload) => { ... },
  )
  .subscribe((status) => {
    console.log('status:', status);
  });
```

using

```ts
const channelId = `_timescaledb_internal:_hyper_4_1_chunk `;
const channel = supabaseClient
  .channel(channelId).on(
    'postgres_changes',
    {
      schema: '_timescaledb_internal',
      event: 'UPDATE',
    },
    (payload) => { ... },
  )
  .subscribe((status) => {
    console.log('status:', status);
  });
```

will work.

As far as I understand about timescale (and I don't really understand that much) the hypertable `public.measures` actually becomes more of a `view` than a `table` so it's not a real table anymore but an abstraction. So I could imagine the reason the subscriptions won't work on `public.measures` directly is because there aren't actually any changes happening so postgres won't send any events or at least not replicate the table properly?!

Generally, that wouldn't be much of a problem as I have my workaround but if I'm not mistaken, subscribing to the chunk `_hyper_4_1_chunk` _will_  become a problem as the the hypertable will eventually switch to a new chunk which will render the subscription non functional.

So my question is about wether there is a way to `fix` this so subscriptions to `public.measures` actually will work and mitigate the "chunk rotation problem"?

**Comment by w3b6x9** [comment]
@jsbrain Realtime works by picking up database changes via logical replication but I don't think it's going be feasible to use Realtime with Timescale.

I found this response by Timescale's CTO regarding the matter: https://www.timescale.com/forum/t/does-timescale-cloud-support-debezium/468/3. Also, Timescale's docs wouldn't recommended using logical replication with it: https://docs.timescale.com/timescaledb/latest/how-to-guides/replication-and-ha/about-ha/#replication.
