### ISSUE TITLE
Pick up from last wal_position

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#34]
When we start the server, it reads from `wal_position` = `{"0", "0"}`:

https://github.com/supabase/realtime/blob/1d7cf1162eb40e5f3c6c9349e2509cd7f7f8914c/server/lib/realtime/application.ex#L33

We need a way for the server to keep track of its position and then pick up where it last read from (if the server dies)

**Comment by kiwicopple** [comment]
I imagine with this one, we are going to need a database of some sort. Ideally it isn't another whole install and can just be done within the server itself. Something like SQLite. I know that elixir also has strong support for mnesia, but that's beyond my knowlege of whether this is a good use case

**Comment by kiwicopple** [comment]
Following my own advice to post on GH:

We may not even need to store state. The master server keeps track of the subscribers progress for purging. It may even be possible to ask the master PG "give me everything from the last time I acknowleged you"

**Comment by fracek** [comment]
From what I understand, at the moment we are using a temporary replication slot, this means that when the client disconnects (e.g. on crash) the replication slot is dropped.

I then tried to look at the `pg_replication_slots` table using a named replication slot

```
postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 abcd      | pgoutput | logical   |  13117 | postgres | f         | t      |       2222 |      |          644 | 0/1696A58   | 0/1696A58
(1 row)
```

When I insert a record from the example web application we can see the `restart_lsn`/`confirmed_flush_lsn` values increment.

```
postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 abcd      | pgoutput | logical   |  13117 | postgres | f         | t      |       2233 |      |          648 | 0/1698080   | 0/1698080
(1 row)
```

I then disconnect the realtime application and manually insert a couple of rows in the users table, the `*_lsn` values don't change since we are not replicating.

```
postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 abcd      | pgoutput | logical   |  13117 | postgres | f         | f      |            |      |          648 | 0/1698080   | 0/1698080
(1 row)
```

When I restart the application (using `xlog/offset = {"0", "0'}`, i.e. what we have now) we start reading the replication log where we left and correctly push the new records to the channels.

```
postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn 
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------
 abcd      | pgoutput | logical   |  13117 | postgres | f         | t      |       2270 |      |          650 | 0/16980B8   | 0/1699530
(1 row)
```

So I think the only real change required is to use named replication slots and not a temporary one, then postgres will do the right thing automatically.

**Comment by kiwicopple** [comment]
that's amazing news. If that's the case, then I believe we can just update this line right?

https://github.com/supabase/realtime/blob/9d24b6010c900dc81d207fc1b7a7e0a0a7a5844f/server/lib/realtime/application.ex#L32

Looks like it from the comments. And according to the comments we can also leave it at `{0, 0}` so that the master can decide what to start sending:

https://github.com/supabase/realtime/blob/9d24b6010c900dc81d207fc1b7a7e0a0a7a5844f/server/lib/realtime/application.ex#L33

So just to confirm, these are the only tasks: (?)

- [ ] update `slot: :temporary` to accept a config var
- [ ] add a config var that reads from ENV (`slot_name = System.get_env("SLOT_NAME") || :temporary`)
- On our servers, add a new ENV var (something like `SLOT_NAME=realtime`)

**Comment by fracek** [comment]
Yes, that's exactly how I plan to implement it!

**Comment by kiwicopple** [comment]
Nice one @fracek 👍

**Comment by awalias** [comment]
@kiwicopple Do I need to add this env var to KPS once we include this latest realtime version?

**Comment by kiwicopple** [comment]
Ah yes please @awalias . The env var is `SLOT_NAME`

**Comment by awalias** [comment]
KPS is shipped and frontend/worker will ship with next deployment
