### ISSUE TITLE
No realtime events are being received by the client

### ISSUE THREAD

**Issue by rbkayz** [supabase/realtime#370]
# Bug report

## Describe the bug

No events are being received by the realtime client

## To Reproduce

Here's a sample code I've written to listen to inserts on a table. Can confirm that replication is on for this table

```
import { supabase } from "./supabaseClient.js";

// For reference, the supabase client that is imported
// export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
//   realtime: {
//     params: {
//       eventsPerSecond: 10,
//     },
//   },
// });

const data = await supabase.auth.signInWithPassword({
  email: "<my-email>",
  password: "<my-password>,
});

supabase
  .channel("public:tbl_message")
  .on("postgres_changes", { event: "INSERT", schema: "public", table: "tbl_message" }, (payload) => {
    console.log("Change received!", payload);
  })
  .subscribe();
```

## Expected behavior

Ideally, the added row should be received as a payload, but I don't receive anything. Please help

**Comment by clonecorp** [comment]
Same. I'll give more details about my config though so maybe @w3b6x9 can actually take a look.

On the cloud solution of Supabase, realtime works, but on the docker version of Supabase, they don't.

I receive this on the server side:
`supabase-realtime | 2022-12-06 14:02:08.911 [info] JOINED realtime:schema-db-changes in 9ms
supabase-realtime |   Parameters: %{"config" => %{"broadcast" => %{"ack" => false, "self" => false}, "postgres_changes" => [%{"event" => "*", "schema" => "public"}], "presence" => %{"key" => ""}}}`

My subscription on the frontend is console logged and this is what I have `state: "joined"`
Running `SELECT  * from pg_publication_tables` in the SQL editor gives me the row which is indeed the one I subscribe to

BUT `realtime.subscription` is empty and the payloads on the frontend don't come.

I am running the docker with a reverse proxy with the URL and anon keys correctly set up.

Any idea why the subscription returns true on the frontend but Postgres doesn't have any record of this?

**Comment by w3b6x9** [comment]
Just to confirm everyone here is talking about Realtime local development via Supabase CLI correct?

I was able to get it working for me. Here's what I did:

1. Made sure I was on latest Supabase CLI: v1.24.0
2. `supabase start`
3. Created a table under `public` schema: `CREATE TABLE test ( id serial primary key );`
4. `ALTER PUBLICATION supabase_realtime ADD TABLE test;`
5. Confirm it: `SELECT * FROM pg_publication_tables;`
6. Listen for changes using supabase-js v2.

**Comment by clonecorp** [comment]
> Just to confirm everyone here is talking about Realtime local development via Supabase CLI correct?
> 
> I was able to get it working for me. Here's what I did:
> 
> 1. Made sure I was on latest Supabase CLI: v1.24.0
> 2. `supabase start`
> 3. Created a table under `public` schema: `CREATE TABLE test ( id serial primary key );`
> 4. `ALTER PUBLICATION supabase_realtime ADD TABLE test;`
> 5. Confirm it: `SELECT * FROM pg_publication_tables;`
> 6. Listen for changes using supabase-js v2.

I am not using the CLI.

I am using the docker container for self-hosting Supabase as described here: https://supabase.com/docs/guides/hosting/docker

I even spun a new VM with Linux and set up everything from scratch with just the docker container and the supabase-js v2 on the frontend, everything works but the realtime. Can you please check @w3b6x9 ?

**Comment by w3b6x9** [comment]
> I am using the docker container for self-hosting Supabase as described here: https://supabase.com/docs/guides/hosting/docker

@clonecorp Ah, I see. That is still stuck on the old Realtime (https://github.com/supabase/supabase/blob/4d609958e8c10c9a7de3cbd5c9afd2768d87efac/docker/docker-compose.yml#L108) that only works with supabase-js v1. I'll need to go update it to the latest (https://hub.docker.com/layers/supabase/realtime/v1.0.0-rc.14/images/sha256-ac28d19087bb1ba382a70b83ccee46f8460d04ec16bdd5cb24ad82959bfdc105?context=explore) to get it working with supabase-js v2.

**Comment by clonecorp** [comment]
> @clonecorp Ah, I see. That is still stuck on the old Realtime (https://github.com/supabase/supabase/blob/4d609958e8c10c9a7de3cbd5c9afd2768d87efac/docker/docker-compose.yml#L108) that only works with supabase-js v1. I'll need to go update it to the latest (https://hub.docker.com/layers/supabase/realtime/v1.0.0-rc.14/images/sha256-ac28d19087bb1ba382a70b83ccee46f8460d04ec16bdd5cb24ad82959bfdc105?context=explore) to get it working with supabase-js v2.

Oh wow, yep, I understand now. I thought something was wrong with my config. That's good to know. Please, let me know when you update it

**Comment by w3b6x9** [comment]
>Please, let me know when you update it

@clonecorp sure thing!

>locally I get nothing when I push updates to a table I'm subscribed to.

@ShaneK can you please share your setup steps so that I may reproduce?

@rbkayz it's unclear if you're having issues with hosted Realtime via Supabase or self-hosting/CLI. If it's the former, please submit a support ticket and I'll take a lookg. If it's the latter, can you provide how you set up Realtime?

**Comment by w3b6x9** [comment]
Can everyone follow the instructions here and see if it resolves your issue? https://github.com/supabase/realtime/issues/372#issuecomment-1358599886. I'm going to close this issue so we can refer to https://github.com/supabase/realtime/issues/372 but feel free to reopen this or create another issue if you have a separate issue.

**Comment by ShaneK** [comment]
Just following up, my issue here was I was using a very old version of the Supabase CLI that was installed with homebrew and I didn't know it
![image](https://user-images.githubusercontent.com/561207/215299984-202e3991-2fc0-41f1-91f0-0cc712ba8ab5.png)
That was causing me to use a very old version of the realtime server, which didn't support the v2 version of supabase. I'm still in the process of pulling new docker images from the current version of the CLI, but I'm sure this will resolve the issue.

Thanks!
