### ISSUE TITLE
Broadcast and Presence Channel Authorization

### ISSUE THREAD

**Issue by w3b6x9** [supabase/realtime#376]
# Feature request

Devs have been clamoring for a way to implement channel-level authorization so clients can join specific channels depending on pre-defined rules.

## Additional context

- https://github.com/supabase/supabase/discussions/8162
- https://github.com/supabase/supabase/discussions/10706

**Comment by msabaeian** [comment]
Hey @w3b6x9, is there any update on this feature? is it part of upcoming plans?

**Comment by w3b6x9** [comment]
@msabaeian pinging @chasers as he's spearheading this

**Comment by nyannyacha** [comment]
I'm looking at recent commits, And I can see you guys working on the channel endpoints. Is that work related to this?

**Comment by nyannyacha** [comment]
@filipecabaco 😋

**Comment by filipecabaco** [comment]
🤣 @nyannyacha spoiler alert I guess?

**Comment by nyannyacha** [comment]
I'm very eagerly awaiting that PR to land! Cheer up guys 😆

**Comment by TuffDev** [comment]
https://github.com/supabase/realtime/pull/796
https://github.com/supabase/realtime/pull/798

Exciting!!

I see the broadcasts table in my realtime schema.  How can I start using this?

**Comment by filipecabaco** [comment]
@TuffDev we're not there yet 😅 

We're now finishing some of the work to allow channel creation ( https://github.com/supabase/realtime/pull/806 ) and then we will need to add all the changes to the client libs but the flow is similar to what you mentioned.

This is the tentative flow we're aiming for at the moment:
* Create a channel via API (we will also let RLS define who can create them)
* Get the RLS rules ready for Channel / Broadcast / Presence (we will want all the features behind this mechanism and it will a table per feature) 
* Set public to false on the configuration

**This is still WIP so there's a high probability of changes**

**Comment by filipecabaco** [comment]
Update: we're opening a PR to have the assumption that if a channel has been created against the API it will be a "private" channel which will end up using the new Authz policies

https://github.com/supabase/realtime/pull/812

**Comment by filipecabaco** [comment]
https://github.com/orgs/supabase/discussions/22484

Please do provide feedback 🎉 

Thank you for all the patience and please do provide feedback. Took a bit longer to do this but we're glad to be releasing it ❤️

**Comment by filipecabaco** [comment]
Closing this, please use the discussion to provide feedback 🙏
