### ISSUE TITLE
Realtime doesn't run on image: realtime/walrus.

### ISSUE THREAD

**Issue by berbagimadani** [supabase/realtime#378]
Realtime doesn't run on image: realtime/walrus.
I tested on another version of supabase/realtime:0.7.1 realtime running fine

## System information
psql (PostgreSQL) 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
Ubuntu 22.04 LTS
Docker version 20.10.22 

## Screenshots
![Screenshot from 2022-12-19 19-21-15](https://user-images.githubusercontent.com/4327476/208425069-545e8b02-63da-421b-846f-f7fc83bf2b68.png)

**Comment by w3b6x9** [comment]
@berbagimadani follow the instructions found here: https://github.com/supabase/realtime/issues/372#issuecomment-1358599886
