### ISSUE TITLE
Realtime stopped working and logs are being flooded with error events

### ISSUE THREAD

**Issue by alexreiling** [supabase/realtime#379]
# Bug report

## Describe the bug
Since a couple of days I noticed that our realtime subscriptions were not working anymore. As far as I could find out, we didn't change anything Realtime-related in supabase or the calling clients. When I checked the Realtime logs the following entry appeared every couple of seconds:
```
Subscribing to PostgreSQL failed: {:badrpc, {:EXIT, {:noproc, {DBConnection.Holder, :checkout, [#PID<51442.7.1993>, []]}}}}
```
Metadata:
```
[
  {
    "callers": [],
    "context": [
      {
        "application": "realtime",
        "domain": [
          "elixir"
        ],
        "file": "lib/realtime_web/channels/realtime_channel.ex",
        "function": "handle_info/2",
        "gl": "<0.2725.0>",
        "line": 302,
        "mfa": [
          "Elixir.RealtimeWeb.RealtimeChannel",
          "handle_info",
          "2"
        ],
        "module": "Elixir.RealtimeWeb.RealtimeChannel",
        "pid": "<0.14728.978>",
        "time": 1670587933490138,
        "vm": [
          {
            "node": "realtime-prod@fdaa:0:cc:a7b:9d35:68f2:3d71:2"
          }
        ]
      }
    ],
    "depth": null,
    "error_logger": [],
    "error_string": null,
    "external_id": "[APP_ID]",
    "formatter_error_params": [],
    "level": "error",
    "logger_pubsub_backend": [],
    "project": "[APP_ID]",
    "request_id": null,
    "stacktrace": [],
    "tenant_params": []
  }
]
```
I have no idea what's happening tbh. Any help or indication where to look for fixing this would be much appreciated.
Thank you in advance

## Screenshots

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/9352422/206699447-557f0193-7edf-494c-8ee0-c30f23c71e20.png">

**Comment by w3b6x9** [comment]
We recently deployed a change to production that should help prevent this issue from coming up: https://github.com/supabase/realtime/pull/374.

If you see this issue again please create a support ticket: https://app.supabase.com/support/new.

**Comment by wizzymotion** [comment]
### I'm facing same error, now in 2024.
My limits were exceeded due to this error, and my services are compromised...

I need Help, pleeease...



<img width="1832" alt="Screenshot 2024-04-15 at 11 03 35" src="https://github.com/supabase/realtime/assets/78563491/2932c7ea-8453-48c5-8e78-e314016673cc">

**Comment by huy-qn** [comment]
> ### I'm facing same error, now in 2024.
> My limits were exceeded due to this error, and my services are compromised...
> 
> I need Help, pleeease...
> 
> <img alt="Screenshot 2024-04-15 at 11 03 35" width="1832" src="https://private-user-images.githubusercontent.com/78563491/322508829-2932c7ea-8453-48c5-8e78-e314016673cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTcwNzksIm5iZiI6MTcxMzQ5Njc3OSwicGF0aCI6Ii83ODU2MzQ5MS8zMjI1MDg4MjktMjkzMmM3ZWEtODQ1My00OGM1LThlNzgtZTMxNDAxNjY3M2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAzMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGJiYzA5NGFlMGIxZTM4ZmE5NTBhNTFlYmVhNTM2NTc1NDFjMDZlOGM2ZmRkZTJiYjEwNDU3OTRjZTNhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXQj7hrCg3ykImhk_hMeR3cpDjqadFzyVooQd1mKqms">

Same issue with me.

It keeps throwing: "Subscribing to PostgreSQL failed".
