### ISSUE TITLE
Add release notes to each release

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#38]
I think we can automate this somehow with `gren`, which should pick up all the issues which were closed between tags

**Comment by kiwicopple** [comment]
This can be done using `semantic-release`, as completed by @soedirgo here in our other repo: https://github.com/supabase/pg-api/blob/9c1501d82199b91d00abdf6644ca961078d4525c/.github/workflows/release.yml#L28

However we will need to figure out if there is a library which can do this with Elixir

Notes from Bobbie:

> On Realtime
> semver is really only meant for repos with a public-facing API, i.e. libraries, not standalone apps. Realtime doesn’t really fit this picture, so we need a different versioning model. I have 2 options:
>    The simplest one is to use semver but without a Major version. This is the most semantic-release-compatible and doesn’t need any modification.
>    Considering realtime’s results are consumed by realtime-js, we can make a BREAKING CHANGE every time realtime forces a significant change to realtime-js, for some definition of significant. But this might confuse some users looking at the header “BREAKING CHANGE” in the release notes.

I think we should stick to the regular strategy of major.minor.patch. It is, in theory, a public API as it is consumed by external libraries. We can bump the minor every time we release a feature, and bump the major if we ever make a full rewrite of the repo

**Comment by soedirgo** [comment]
Closed by #57.
