### ISSUE TITLE
Filter on DELETE event not work?

### ISSUE THREAD

**Issue by denchic45** [supabase/realtime#397]
# Bug report

## Describe the bug

When listening for deletes in a table, the filter is ignored

## To Reproduce
I am using a kotlin library. I get updates on all deletes from the table, regardless of the filterю
```kotlin
suspend fun observeDeletesByRole(role: String) {
        val channel = realtime.createChannel("#users")
        val flow: Flow<PostgresAction.Delete> = channel.postgresChangeFlow(schema = "public") {
            table = "user"
            filter = "role=eq.${role}"
        }
        channel.join()
        flow.collect {
            /*...*/
        }
    }
```
I also enabled full replication for the table:
```alter table user replica identity full;```

## Expected behavior
Only those updates that match the filter should come

**Comment by w3b6x9** [comment]
@denchic45 we're planning on adding this: https://github.com/supabase/walrus/issues/53

**Comment by denchic45** [comment]
@w3b6x9 Got it, thanks for the info!
