### ISSUE TITLE
Forward traffic through Node.js server to mobile client

### ISSUE THREAD

**Issue by bryan-vh** [supabase/realtime#398]
# Feature request

## Describe the example you'd like

Hello! I'd like to understand if it's possible to forward changes on the Realtime server through a Node.js server to an iOS client. I was thinking of connecting the realtime server with the js library on my Node.js server using `RealtimeClient` and then using normal WebSockets to connect from the iOS client. I'm not sure if this is feasible and would like to know if I'm on the right path and if there are any examples of this use-case. Thanks!

I had planned to create a WebSocket adapter specifically for Supabase Realtime in NestJS by doing the following:

```typescript
export class SupabaseRealtimeAdapter implements WebSocketAdapter {
  constructor(private readonly configService: ConfigService) {}

  create() {
    const realtimeUrl = this.configService.get<string>('supabase.realtimeUrl');
    const options: RealtimeClientOptions = { logger: this.logger.log };
    return new RealtimeClient(realtimeUrl, options);
  }

  bindClientConnect(server: RealtimeClient) {
    server.connect();
    console.log('connected to supabase!');
  }

  bindMessageHandlers(
    client: WebSocket,
    handlers: MessageMappingProperties[],
    transform: (data: any) => Observable<any>,
  ) {
    console.log('message received (forward data here maybe?)');
  }

  close(server: RealtimeClient) {
    server.disconnect();
  }

  private readonly logger = new Logger(SupabaseRealtimeAdapter.name);
}
```

Unfortunately, it seems that this may create a single `RealtimeClient` that will then be connected to from multiple iOS WebSocket clients, which may cause undue stress. However, with channels, it may be possible to create a 1:1 relationship between socket to channel and then mimic that relationship when subscribing / unsubscribing from a mobile client.

## Additional context

iOS App Client < - > Node.js server < - > Realtime server

**Comment by w3b6x9** [comment]
@bryan-vh you can definitely do this but why? what's preventing you from connecting client and Realtime server directly?

**Comment by w3b6x9** [comment]
@bryan-vh closing b/c you created a discussion for this: https://github.com/supabase/supabase/discussions/11386

**Comment by bryan-vh** [comment]
@w3b6x9 I can't do this because there isn't official support for connecting the Realtime server to a Swift iOS client, only JS and flutter, no?

**Comment by w3b6x9** [comment]
@bryan-vh there are community swift client libs that wrap Realtime functionality. Have you come across https://github.com/supabase-community/realtime-swift or https://github.com/supabase-community/supabase-swift.

**Comment by w3b6x9** [comment]
@bryan-vh ah, looks like you're aware: https://github.com/supabase-community/supabase-swift/issues/54. which strategy have you decided to go with?

**Comment by bryan-vh** [comment]
@w3b6x9 I've decided to go with Flutter since that platform is already supported and will allow me to support both iOS and Android.
