### ISSUE TITLE
Realtime has the following error logging

### ISSUE THREAD

**Issue by zhushuihua** [supabase/realtime#432]
In self-hosting, realtime database has the following error logging and the realtime database can't be used.

realtime-dev.supabase-realtime | 09:01:16.257 [info] Starting Elixir.Realtime.RateCounter for: {:limit, :tenant_events, "realtime-dev"}
realtime-dev.supabase-realtime | 09:01:16.258 [info] Starting Elixir.Realtime.RateCounter for: {:limit, :channel_joins, "realtime-dev"}
realtime-dev.supabase-realtime | 09:01:16.260 [debug] Starting postgres stream extension with args: %{
realtime-dev.supabase-realtime |   "db_host" => "QhixI0o7PYIABziLUL4f0A==",
realtime-dev.supabase-realtime |   "db_name" => "sWBpZNdjggEPTQVlI52Zfw==",
realtime-dev.supabase-realtime |   "db_password" => "oLhfTtyhNGE+vbSd1wxeHN5whqJiSbh6Wk5COCsTeTUoy0l+TUxtnYrwHXy59x5F",
realtime-dev.supabase-realtime |   "db_port" => "+enMDFi1J/3IrrquHHwUmA==",
realtime-dev.supabase-realtime |   "db_socket_opts" => [:inet],
realtime-dev.supabase-realtime |   "db_user" => "sWBpZNdjggEPTQVlI52Zfw==",
realtime-dev.supabase-realtime |   "id" => "realtime-dev",
realtime-dev.supabase-realtime |   "ip_version" => 4,
realtime-dev.supabase-realtime |   "poll_interval_ms" => 100,
realtime-dev.supabase-realtime |   "poll_max_changes" => 100,
realtime-dev.supabase-realtime |   "poll_max_record_bytes" => 1048576,
realtime-dev.supabase-realtime |   "publication" => "supabase_realtime",
realtime-dev.supabase-realtime |   "region" => "us-east-1",
realtime-dev.supabase-realtime |   "slot_name" => "supabase_realtime_replication_slot",
realtime-dev.supabase-realtime |   "subs_pool_size" => 5
realtime-dev.supabase-realtime | }
realtime-dev.supabase-realtime | 09:01:16.284 [error] Could not create schema migrations table. This error usually happens due to the following:
realtime-dev.supabase-realtime | 
realtime-dev.supabase-realtime |   * The database does not exist
realtime-dev.supabase-realtime |   * The "schema_migrations" table, which Ecto uses for managing
realtime-dev.supabase-realtime |     migrations, was defined by another library
realtime-dev.supabase-realtime |   * There is a deadlock while migrating (such as using concurrent
realtime-dev.supabase-realtime |     indexes with a migration_lock)

**Comment by w3b6x9** [comment]
@zhushuihua can you share setup steps so we can reproduce?

**Comment by zhushuihua** [comment]
The same code can work with supabase official SAAS without any issues. But for the self hosting one, it never CLICKED.

**Comment by zhushuihua** [comment]
I used the latest supabase image

**Comment by w3b6x9** [comment]
@zhushuihua can you make sure that you tear everything down, including volumes, and try again?

Realtime runs migrations inside the `realtime` schema on an initial client subscription. For some reason, it looks like those migrations are not being properly applied. Can you take a look inside `realtime` schema and see if you have a `schema_migrations` table?

**Comment by zhushuihua** [comment]
Everytime I install Supabase, I used a clean droplet from digital ocean and did a clean installation every with different OS versions. All result in the same error.

**Comment by zhushuihua** [comment]
More error loggings for fyi..
 06:41:45.302 [info] PostgresCdcRls terminated: "realtime-dev" realtime@127.0.0.1
realtime-dev.supabase-realtime  | 06:41:45.303 project=realtime-dev external_id=realtime-dev [error] Error starting Postgres Extention: {:error,
realtime-dev.supabase-realtime  |  {:shutdown,
realtime-dev.supabase-realtime  |   {:failed_to_start_child, Extensions.PostgresCdcRls.Migrations,
realtime-dev.supabase-realtime  |    {%Postgrex.Error{
realtime-dev.supabase-realtime  |       message: nil,
realtime-dev.supabase-realtime  |       postgres: %{
realtime-dev.supabase-realtime  |         code: :insufficient_privilege,
realtime-dev.supabase-realtime  |         file: "aclchk.c",
realtime-dev.supabase-realtime  |         line: "3447",
realtime-dev.supabase-realtime  |         message: "permission denied for schema realtime",
realtime-dev.supabase-realtime  |         pg_code: "42501",
realtime-dev.supabase-realtime  |         position: "28",
realtime-dev.supabase-realtime  |         routine: "aclcheck_error",
realtime-dev.supabase-realtime  |         severity: "ERROR",
realtime-dev.supabase-realtime  |         unknown: "ERROR"
realtime-dev.supabase-realtime  |       },
realtime-dev.supabase-realtime  |       connection_id: 1246,
realtime-dev.supabase-realtime  |       query: nil
realtime-dev.supabase-realtime  |     },
realtime-dev.supabase-realtime  |     [
realtime-dev.supabase-realtime  |       {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
realtime-dev.supabase-realtime  |        [
realtime-dev.supabase-realtime  |          file: 'lib/ecto/adapters/sql.ex',
realtime-dev.supabase-realtime  |          line: 932,
realtime-dev.supabase-realtime  |          error_info: %{module: Exception}
realtime-dev.supabase-realtime  |        ]},
realtime-dev.supabase-realtime  |       {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]},
realtime-dev.supabase-realtime  |       {Ecto.Adapters.SQL, :execute_ddl, 4,
realtime-dev.supabase-realtime  |        [file: 'lib/ecto/adapters/sql.ex', line: 1024]},
realtime-dev.supabase-realtime  |       {Ecto.Migrator, :verbose_schema_migration, 3,
realtime-dev.supabase-realtime  |        [file: 'lib/ecto/migrator.ex', line: 696]},
realtime-dev.supabase-realtime  |       {Ecto.Migrator, :lock_for_migrations, 4,
realtime-dev.supabase-realtime  |        [file: 'lib/ecto/migrator.ex', line: 510]},
realtime-dev.supabase-realtime  |       {Ecto.Migrator, :run, 4, [file: 'lib/ecto/migrator.ex', line: 422]},
realtime-dev.supabase-realtime  |       {Realtime.Repo, :with_dynamic_repo, 2,
realtime-dev.supabase-realtime  |        [file: 'lib/realtime/repo.ex', line: 22]},
realtime-dev.supabase-realtime  |       {Extensions.PostgresCdcRls.Migrations, :init, 1,
realtime-dev.supabase-realtime  |        [file: 'lib/extensions/postgres_cdc_rls/migrations.ex', line: 18]}
realtime-dev.supabase-realtime  |     ]}}}}

**Comment by zhushuihua** [comment]
> @zhushuihua can you make sure that you tear everything down, including volumes, and try again?
> 
> Realtime runs migrations inside the `realtime` schema on an initial client subscription. For some reason, it looks like those migrations are not being properly applied. Can you take a look inside `realtime` schema and see if you have a `schema_migrations` table?

There is no schema_migrations table.

**Comment by clonecorp** [comment]
> Realtime runs migrations inside the `realtime` schema on an initial client subscription. For some reason, it looks like those migrations are not being properly applied. Can you take a look inside `realtime` schema and see if you have a `schema_migrations` table?

I just installed a fresh instance of Supabase. In the `realtime` schema, no table was created. On the other hand, the `_realtime` schema gets created and has 3 tables in it, including `schema_migrations` with rows in it.

**Comment by w3b6x9** [comment]
@zhushuihua @clonecorp I found the issue. Self-hosting Realtime is using the `postgres` role but needs to be `supabase_admin` due to `postgres` role not having the proper permissions to deal with `realtime` schema and its relations.

Will push up a PR shortly and link it here but you can unblock yourself now by changing `${POSTGRES_USER}` to `supabase_admin` here: https://github.com/supabase/supabase/blob/b0ed9a425b81a8de5467a44939d034a21f840744/docker/docker-compose.yml#L117
