### ISSUE TITLE
Format self-hosted URL

### ISSUE THREAD

**Issue by kjell-van-straaten** [supabase/realtime#457]
# Improve documentation

## Link 

[Readme.md
](https://github.com/supabase/realtime#readme)

## Describe the problem

It is unclear how to format the URL in order to connect to a self-hosted realtime socket. I have tried a bunch of options and none seemed to work. The closest I got was using the following URL:
`"wss://{INTERNAL DNS}/realtime/v1/websocket?apikey={SUPABASE_KEY}&vsn=1.0.0"` 

I do not know how to incorporate the external_tenant ID, as prescribed in the README.
I tried `"wss://{EXTERNAL_ID}.{INTERNAL DNS}/realtime/v1/websocket?apikey={SUPABASE_KEY}&vsn=1.0.0"` but it appears the python client cannot deal with this format.

connecting like this: `f"ws://192.168.1.157:4000/socket/websocket?vsn=1.0.0&apikey={SUPABASE_KEY}"` gives me the error that tenant 192 is not found.
However, then I get getaddr info failed for when i change it to `f"ws://{external_id}.192.168.1.157:4000/socket/websocket?vsn=1.0.0&apikey={SUPABASE_KEY}"`

**EDIT**
I did a little hacking; I added a new tenant with external ID 192 to ensure i can use the tenant from outside the VM that runs supabase. I now get the following error:

`15:39:30.349 project=192 external_id=192 [error] Error starting Postgres Extention: {:error,
 {:shutdown,
  {:failed_to_start_child, Extensions.PostgresCdcRls.Migrations,
   {%Postgrex.Error{
      message: nil,
      postgres: %{
        code: :duplicate_object,
        file: "typecmds.c",
        line: "1170",
        message: "type \"equality_op\" already exists",
        pg_code: "42710",
        routine: "DefineEnum",
        severity: "ERROR",
        unknown: "ERROR"
      },
      connection_id: 8454,
      query: nil
    },
    [
      {Ecto.Adapters.SQL, :raise_sql_call_error, 1,
       [
         file: 'lib/ecto/adapters/sql.ex',
         line: 932,
         error_info: %{module: Exception}
       ]},
      {Enum, :"-map/2-lists^map/1-0-", 2, [file: 'lib/enum.ex', line: 1658]},
      {Ecto.Adapters.SQL, :execute_ddl, 4,
       [file: 'lib/ecto/adapters/sql.ex', line: 1024]},
      {Ecto.Migration.Runner, :log_and_execute_ddl, 3,
       [file: 'lib/ecto/migration/runner.ex', line: 352]},
      {Ecto.Migration.Runner, :"-flush/0-fun-1-", 6,
       [file: 'lib/ecto/migration/runner.ex', line: 117]},
      {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
       [file: 'lib/enum.ex', line: 2468]},
      {Ecto.Migration.Runner, :flush, 0,
       [file: 'lib/ecto/migration/runner.ex', line: 116]},
      {Ecto.Migration.Runner, :perform_operation, 3,
       [file: 'lib/ecto/migration/runner.ex', line: 289]}
    ]}}}}`

Hope you can help.

## Describe the improvement

URL formulation guide.

**Comment by w3b6x9** [comment]
@kjell-van-straaten just a heads up that the newest version of Realtime (v2), which is what the README is referring to, doesn't yet work with Python client b/c it's not been updated to work with Realtime v2. If you don't care for Broadcast and Presence you can refer to Realtime v1: https://github.com/supabase/realtime/tree/v1.

>  I now get the following error:
> 
> 15:39:30.349 project=192 external_id=192 [error] Error starting Postgres Extention: {:error, {:shutdown, {:failed_to_start_child, Extensions.PostgresCdcRls.Migrations, {%Postgrex.Error{ message: nil, postgres: %{ code: :duplicate_object, file: "typecmds.c", line: "1170", message: "type \"equality_op\" already exists"

Make sure you are tear everything down and start everything from scratch in terms of the Docker volume. That's related to a series of migrations that failed somewhere and now there's an existing type that Postgres is trying to recreate but it can't b/c it already exists.

**Comment by kjell-van-straaten** [comment]
Switching to realtime v1 solved this issue. Thanks!
