### ISSUE TITLE
Realtime 2.x not working in docker-compose setup

### ISSUE THREAD

**Issue by jojomatik** [supabase/realtime#462]
# Bug report

## Describe the bug

The realtime container is unhealthy.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml
2. Set up project environment variables and relevant files
3. Start stack
4. See error `/app/limits.sh: 4: ulimit: error setting limit (Operation not permitted)`

## Expected behavior

No error, service healthy.

## Screenshots

Not applicable

## System information

- OS: official docker image v2.1.0

## Additional context

The stack was working fine before the upgrade to 2.1.0, other services start fine.

**Comment by w3b6x9** [comment]
@jojomatik we have a fix for this that we're waiting to release: https://github.com/supabase/realtime/pull/460.

**Comment by w3b6x9** [comment]
@jojomatik we're planning on a release in the next 24 hours.

**Comment by jojomatik** [comment]
Nice, thank you!

**Comment by w3b6x9** [comment]
@jojomatik the release has been delayed and we'll make sure to update this issue when it's live in production.

**Comment by jojomatik** [comment]
No problem, thanks for the info! I'll deploy with v1 then for now and upgrade later, thanks!

**Comment by w3b6x9** [comment]
@jojomatik we just did a release a couple of hours ago. You can set env var `RLIMIT_NOFILE` to an empty string and it should work in rootless mode for you.

**Comment by jojomatik** [comment]
Sorry for the late reply @w3b6x9 

Thanks for the fix and release :) I've just tested, the docker container starts and is healthy, thanks. Should we add the new version and parameter to the docs/ the compose file?

I can't connect from the client though. 

This might seem obvious, but it seems like supabase/realtime-js@2 is required. Is this true?

If so, is it possible to update realtime-js only to v2 or do I need to migrate the complete supabase-js stack?

**Comment by zachblume** [comment]
Hey all! I just pulled the latest docker-compose.yml from the /docker folder of the supabase and ran it with root priveleges in the newest Amazon Linux AMI and it failed with this error. Setting docker-compose env variable RLIMIT_NOFILE to empty string fixed it. Why would that still be happening?
