### ISSUE TITLE
Refreshing the access token

### ISSUE THREAD

**Issue by shankar-narayanan-d** [supabase/realtime#490]
## Describe the problem

The readme file says we can use a jwt token as API_KEY for creating a client, but if the exp in token expires I am not able to get realtime updates.

**Comment by w3b6x9** [comment]
@shankar-narayanan-d are you using standalone Realtime server or using one of the Realtime clients? Are you using a hosted Supabase project or self-hosting? Can you please provide context around your use case?

**Comment by shankar-narayanan-d** [comment]
> @shankar-narayanan-d are you using standalone Realtime server or using one of the Realtime clients? Are you using a hosted Supabase project or self-hosting? Can you please provide context around your use case?

I have self hosted this repo: https://github.com/supabase/realtime

**Comment by w3b6x9** [comment]
@shankar-narayanan-d you will have to manage refreshing tokens yourself. Which client are you using? What did you end up doing?

**Comment by shankar-narayanan-d** [comment]
I stopped using self-hosting. Now I am working on supabase hosted service.
I am using @supabase/supabase-js client.
I am using a custom access token for authentication.
How will I be able to refresh the token

**Comment by w3b6x9** [comment]
> How will I be able to refresh the token

Again, you will have to do this yourself since you're working with custom tokens. See this thread for context: https://github.com/supabase/supabase-js/issues/553#issuecomment-1493889451
