### ISSUE TITLE
`in` filter not working when using int or uuid

### ISSUE THREAD

**Issue by DanMossa** [supabase/realtime#491]
I originally thought this was a flutter issue but @vinzent03 was able to reproduce it using the supabase cli.

Original ticket here:
https://github.com/supabase/supabase-flutter/issues/359

**Comment by Vinzent03** [comment]
To give a bit more insight. I was still using the dart client to call the realtime api, but afaik there is no further processing of the filter value.

```dart
    Supabase.instance.client.channel('public:test').on(
      RealtimeListenTypes.postgresChanges,
      ChannelFilter(
        event: 'INSERT',
        schema: 'public',
        table: "test",
        filter: 'uid=in.(179fb88b-f105-4f41-9bf6-e68f615d5c2e)',
      ),
      (payload, [ref]) {
        print('New message received: ${payload.toString()}');
      },
    ).subscribe();
```
The `in` filter works for a single `uuid` value, but not for more.
The `in` filter doesn't work at all for `int` values.
It works for `text` values.

**Comment by w3b6x9** [comment]
@DanMossa @Vinzent03 thanks for the issue and the additional context. we'll investigate.

**Comment by gitboss** [comment]
Can concur with @Vinzent03 I tested with `varchar` and `int`. `in` filter works with `varchar` and not at all with `int`

**Comment by w3b6x9** [comment]
we have a pr open to address this: https://github.com/supabase/realtime/pull/526
