### ISSUE TITLE
Version number is hardcoded

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#51]
![image](https://user-images.githubusercontent.com/458736/83734944-3f871c80-a682-11ea-8a99-03634a1e8572.png)

**Comment by soedirgo** [comment]
Hmm, I don't think there's an easy way around this. I've looked into high profile Elixir projects (Phoenix, Credo, Distillery, HTTPoison), and none of them used automated solutions.

There are some prior art from the JS world: `version` isn't required at build time, so some projects like Docusaurus don't set this. I also recall some automated versioning solution that simply set it to "0.0.0-automated" or similar, it's automatically set before publishing to npm and isn't committed to the repo.

I *can* do some hack with something like [this](https://github.com/aforward/version_tasks), but I'm not sure if it's worth it.

For now I'll remember to make a "bump" commit just before every tag push.

**Comment by kiwicopple** [comment]
Good idea Bobby - for this task, let's just document down the release steps (maybe in RELEASE.md?) and then we can close this one up

**Comment by soedirgo** [comment]
Releasing instructions have been updated on README.md, so closing this issue 🎉
