### ISSUE TITLE
"Billing metrics" being logged ~100 times per minute

### ISSUE THREAD

**Issue by kylerummens** [supabase/realtime#529]
# Bug report

## Describe the bug

I'm seeing the same log in the Realtime section of the logs page: `Billing metrics: [:realtime, :connections]`. This log seems to be occurring multiple times per second. At the time of seeing this, there are only 3 active users on the web app, so I can't imagine that many realtime requests are coming from the users.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Screenshots

<img width="805" alt="Screenshot 2023-03-01 at 8 48 31 PM" src="https://user-images.githubusercontent.com/58995471/222326352-524f26d4-6334-4289-a894-43fca4bb94a9.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Here's something else that might be related. I'm looking at the new Query Performance report page and I'm seeing that there is a query being called about 100 times per minute. The `Role` field says `supabase_admin` and `Time Consumed` says `46.9%`. Here is the query:

```sql
with pub as (
    select
      concat_ws(
        $5,
        case when bool_or(pubinsert) then $6 else $7 end,
        case when bool_or(pubupdate) then $8 else $9 end,
        case when bool_or(pubdelete) then $10 else $11 end
      ) as w2j_actions,
      coalesce(
        string_agg(
          realtime.quote_wal2json(format($12, schemaname, tablename)::regclass),
          $13
        ) filter (where ppt.tablename is not null),
        $14
      ) w2j_add_tables
    from
      pg_publication pp
      left join pg_publication_tables ppt
        on pp.pubname = ppt.pubname
    where
      pp.pubname = $1
    group by
      pp.pubname
    limit $15
  ),
  w2j as (
    select
      x.*, pub.w2j_add_tables
    from
      pub,
      pg_logical_slot_get_changes(
        $2, $16, $3,
        $17, $18,
        $19, $20,
        $21, $22,
        $23, $24,
        $25, $26,
        $27, pub.w2j_actions,
        $28, pub.w2j_add_tables
      ) x
  )
  select
    xyz.wal,
    xyz.is_rls_enabled,
    xyz.subscription_ids,
    xyz.errors
  from
    w2j,
    realtime.apply_rls(
      wal := w2j.data::jsonb,
      max_record_bytes := $4
    ) xyz(wal, is_rls_enabled, subscription_ids, errors)
  where
    w2j.w2j_add_tables <> $29
    and xyz.subscription_ids[$30] is not null
```

I can tell this has to do with replication, but I can't figure out why it's being called so often. This query is being run while there are currently 3 or so active users.

For reference, I set up a custom publication to stream data for three tables to a separate server, but the data in those tables only change once per day.

**Comment by kylerummens** [comment]
Link to original Discord discussion: https://discord.com/channels/839993398554656828/1080684839516242030/1080684839516242030

**Comment by w3b6x9** [comment]
@kylerummens you can ignore the frequency of these kind of logs b/c we poll for these metrics. If you examine the log closely, you'll see your actual Realtime consumption.

<img width="1150" alt="Screenshot 2023-03-02 at 16 27 48" src="https://user-images.githubusercontent.com/5532241/222600260-0055c3ca-d01a-4cb3-b030-1a8888e9b681.png">

So you may see it often in your logs but if you look at the details it'll tell you how many connections you're actually consuming. You can refer to `connected_cluster`.

As for the query, that's the query that we use to poll your database for Realtime changes so what you're seeing is correct as long as you have at least one connected Realtime client.

**Comment by GaryAustin1** [comment]
@w3b6x9 
Can you clarify what you mean by "poll your database"?   Is that in response to a change that goes out to realtime thru replication?  Or are you literally polling the database for changes?

**Comment by w3b6x9** [comment]
@GaryAustin1 as long as there's at least one connected client, Realtime will literally poll your database for changes with the query above. 

It first checks for changes every 100ms by default, and when there's changes, Realtime will subsequently poll immediately instead of waiting 100ms. Then when there are no more changes, Realtime will subsequently revert back to polling every 100ms.
