### ISSUE TITLE
A Rust implementation?

### ISSUE THREAD

**Issue by teymour-aldridge** [supabase/realtime#55]
I noticed that there is a Rust implementation of the Postgres client, but not for the server. I think that the server would benefit from the speed a Rust implementation (possibly more than the client) could bring.
This should maybe be in [the realtime repository](https://github.com/supabase/realtime) instead.

**Comment by kiwicopple** [comment]
I'm going to close this one @teymour-aldridge , but feel free to reopen if you have any other questions
