### ISSUE TITLE
Add self-hosting instructions

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#56]
AWS: https://aws.amazon.com/marketplace/pp/B089N4FH7N/
DO: https://marketplace.digitalocean.com/apps/supabase-realtime
Docker: https://hub.docker.com/r/supabase/realtime

Realtime was released to the marketplaces, which means it is now simpler to get started. We should start documenting the process for hosting and installing Realtime. 

I think we should move this documentation [onto our website](https://supabase.io/docs/realtime/realtime-install), but using the same conventions that we used for postgres: https://github.com/supabase/postgres/wiki

We should end up with 5 pages:

```
- Realtime
  |- About
  |- Docker
  |- AWS
  |- Digital Ocean
  |- Build from scratch
```

**Comment by soedirgo** [comment]
Closed by [supabase/supabase#114](https://github.com/supabase/supabase/pull/114).
