### ISSUE TITLE
Postgresql logs unreadable in development due to realtime query polling

### ISSUE THREAD

**Issue by evelant** [supabase/realtime#565]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When developing locally using `supabase start` the postgresql logs are mostly unreadable due to the constant output of queries polled by realtime. 

There have been other issues filed about this but they all appear to be closed without a sufficient solution (I don't consider disabling nearly all logging via `log_statement fatal` to be a real solution, that just hides the problem along with all other useful logging).

 https://github.com/supabase/realtime/issues/231 
https://github.com/supabase/supabase/issues/5505
 https://github.com/graphile/postgraphile/issues/1456 
 https://github.com/supabase/supabase/issues/9378

## To Reproduce

1. `supabase start`
2. enable realtime on tables, connect a client
3. find current log file with `select pg_current_logfile();`
4. tail the log file in the docker container for the postgres database
5. Observe that it isn't really usable due to realtime query polling output 

## Expected behavior

Postgres logs should be usable in some form or another during development.

## Screenshots

The constantly repeated polled query in the logs looks like this

```
2023-03-27 17:59:59.935 UTC,"postgres","postgres",744,"172.20.0.6:51648",6421d6eb.2e8,12394,"SELECT",2023-03-27 17:48:27 UTC,19/6231,0,LOG,00000,"starting logical decoding for slot ""supabase_realtime_replication_slot_""","Streaming transactions committing after 0/5DD2160, reading WAL from 0/5DD2128.",,,,,"with pub as (
        select
          concat_ws(
            ',',
            case when bool_or(pubinsert) then 'insert' else null end,
            case when bool_or(pubupdate) then 'update' else null end,
            case when bool_or(pubdelete) then 'delete' else null end
          ) as w2j_actions,
          coalesce(
            string_agg(
              realtime.quote_wal2json(format('%I.%I', schemaname, tablename)::regclass),
              ','
            ) filter (where ppt.tablename is not null and ppt.tablename not like '% %'),
            ''
          ) w2j_add_tables
        from
          pg_publication pp
          left join pg_publication_tables ppt
            on pp.pubname = ppt.pubname
        where
          pp.pubname = $1
        group by
          pp.pubname
        limit 1
      ),
      w2j as (
        select
          x.*, pub.w2j_add_tables
        from
          pub,
          pg_logical_slot_get_changes(
            $2, null, $3,
            'include-pk', 'true',
            'include-transaction', 'false',
            'include-timestamp', 'true',
            'include-type-oids', 'true',
            'format-version', '2',
            'actions', pub.w2j_actions,
            'add-tables', pub.w2j_add_tables
          ) x
      )
      select
        xyz.wal,
        xyz.is_rls_enabled,
        xyz.subscription_ids,
        xyz.errors
      from
        w2j,
        realtime.apply_rls(
          wal := w2j.data::jsonb,
          max_record_bytes := $4
        ) xyz(wal, is_rls_enabled, subscription_ids, errors)
      where
        w2j.w2j_add_tables <> ''
        and xyz.subscription_ids[1] is not null",,,"realtime_rls","client backend",,-6966946829329473178
```

## System information

- OS: N/A
- Browser (if applies)  N/A
- Version of supabase cli: 1.45.2
- Version of Node.js: 16.19.0

## Additional context

Perhaps an alternate solution would be to make the logs explorer available from the development UI? It's quite useful in production instances and it's a shame that it's missing from development.

**Comment by w3b6x9** [comment]
@evelant we explored this in great detail last time we visited this but unfortunately we didn't find another good way.

However, I think the logs explorer will be added in the upcoming weeks so that might be a good alternative. You can track the development on this PR: [feat: initial local logflare integration #13166
](https://github.com/supabase/supabase/pull/13166)

**Comment by w3b6x9** [comment]
@evelant we are also going to wrap this polling query in a function and set the log level to fatal on the function level: https://github.com/supabase/realtime/pull/566.
