### ISSUE TITLE
Realtime argument out of range error

### ISSUE THREAD

**Issue by tommy-b-10** [supabase/realtime#569]
# Bug report

Receiving the below error when attempting to connect to my realtime instance. This is using Supabase-Swift, but it also occurs when using the realtime inspector. I'll note that before this I was getting an error about non-alphabet letters being used in the JWT secret, but I resolved this by changing the secret to no use hyphens, '-'.

My Supabase instance is using the [default docker compose](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml), however I have updated realtime to 2.11.0 to try and solve this issue with no affect.

I have added a new tenant 'realtime' and matched in the kong.yml settings to use this instead of 'realtime-dev' as that was pointing elsewhere.

```
13:16:19.118 [error] #PID<0.3713.0> running RealtimeWeb.Endpoint (connection #PID<0.3642.0>, stream id 4) terminated
Server: realtime.supabase-realtime:4000 (http)
Request: GET /socket/websocket?apikey=eyJhbGciOiJIUzI1NiIsInR5cCy6IkpXVCJ9.ewogICAgInJvbGUiOiAiYW5vbiIsCiAgICAiaXNzIjogInN1cGFiYXNlIiwKICAgICJpYXQiOiAxNjgwMTgzMDAwLAogICAgImV4cCI6IDE4MzgwMzU4MDAKfQ.3pZ0l4at4JAZUkQmSX6Q0D0sjIqL5eGEPbj1XzqTlpk&X-Client-Info=supabase-swift/0.2.0
** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 3rd argument: out of range

        (stdlib 4.3) :binary.part(<<249, 135, 251, 41, 76, 194, 15, 133, 90, 41, 78, 112, 74, 134, 74, 147>>, 0, -131)
        (realtime 2.10.2) lib/realtime/helpers.ex:177: Realtime.Helpers.unpad/1
        (realtime 2.10.2) lib/realtime_web/channels/user_socket.ex:50: RealtimeWeb.UserSocket.connect/3
        (phoenix 1.6.13) lib/phoenix/socket.ex:550: Phoenix.Socket.user_connect/6
        (phoenix 1.6.13) lib/phoenix/socket.ex:438: Phoenix.Socket.__connect__/3
        (phoenix 1.6.13) lib/phoenix/transports/websocket.ex:33: Phoenix.Transports.WebSocket.connect/4
        (phoenix 1.6.13) lib/phoenix/endpoint/cowboy2_handler.ex:22: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

## System information

- OS: Linux/Docker
- Realtime v2.11.0

**Comment by w3b6x9** [comment]
@tommy-b-10 ah, so the only tenant you can't use is `realtime` b/c Realtime uses that internally. You can name it anything else though.
