### ISSUE TITLE
[BUG] PostgresCdcRls ||| realtime just stops working randomly in production, happens once a week or so

### ISSUE THREAD

**Issue by Geczy** [supabase/realtime#570]
# Bug report

https://discord.com/channels/839993398554656828/1091719779104084128

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

added some images including my subscription code. im logging the subscription notices and no error was shown about it going offline. 

i magnified the offline period, it was between 04:50 and 12:56 (when i noticed, rebooted, and the server started processing new sign ups again). 

the actual period when it stopped working would have been between 04:50 (a new user that did get sent to my server via realtime sub) and 07:30 (a new user that didn't get sent to my server via realtime sub)

every new user after 04:50 also didn't get sent (there was about 10). i rebooted the server at 12:51:10 and realtime started working again

timestamps are in UTC

## To Reproduce

No idea

## Expected behavior

Subscription throws an errors and resubscribes via supabase client, as it does for other similar errors in supabase

## Screenshots

![image](https://media.discordapp.net/attachments/1091719779104084128/1091719779313782785/image.png?width=1090&height=885)

![image](https://media.discordapp.net/attachments/1091719779104084128/1091719779598991380/image.png?width=1539&height=885)

![image](https://media.discordapp.net/attachments/1091719779104084128/1091719779825504336/image.png?width=1137&height=885)

![image](https://media.discordapp.net/attachments/1091719779104084128/1091719780085534730/image.png?width=1845&height=885)

## System information

- OS: ec2 amazon linux
- Browser (if applies) this is a nodejs backend server
- Version of supabase-js: [e.g. 6.0.2]  `"@supabase/supabase-js": "^2.10.0",`
- Version of Node.js: [e.g. 10.10.0] `FROM node:19.4-alpine as base`

## Additional context

see attached realtime errors i found, i can't confirm this was between the timestamps i noticed supabase to not send realtime logs though. im not sure what timezone this csv is in. but its the only errors i found in realtime logs on dashboard in the last 24 hours. [supabase_logs.csv](https://github.com/supabase/realtime/files/11129735/supabase_logs.csv)

![image](https://user-images.githubusercontent.com/1036968/229294945-7fa510fc-72fc-4c0d-90f2-0b18382c4d64.png)

my specific subscription is at https://github.com/dotabod/backend/blob/master/packages/twitch/events/src/db/watcher.ts#L77

**Comment by mqp** [comment]
My project also sees this same result in the logs.

**Comment by filipecabaco** [comment]
Hi @Geczy 

We've switch our deployment to a new set of machines that should reduce this type of issue. If it occurs again please to report it to https://supabase.com/dashboard/support/new 

Thank you

**Comment by goodacres** [comment]
Hey @filipecabaco - sorry for pinging you on here. Appreciate this issue is closed so just let me know if I should open another one.

As per your last comment - I wondered if you know of any network related issues between clients and supabase realtime that randomly cause subscriptions to close? We've been experiencing this issue sporadically and are trying to pin down root cause.

Any info you may be able to share would be much appreciated. Thanks!

**Comment by filipecabaco** [comment]
hey @goodacres 

No worries! We haven't noticed anything different but can you please open a support ticket so we can better check your project?
