### ISSUE TITLE
Presence Events not showing in Realtime Logs not showing even with `log_level: "info"`

### ISSUE THREAD

**Issue by karandwivedi42** [supabase/realtime#572]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using realtime presence feature, the logs do not appear in [Realtime Logs](https://app.supabase.com/project/project-id/logs/realtime-logs)

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/9624554/230619892-cb46c5ed-ac6f-4ad5-ba3d-96d99d9affab.png">

## To Reproduce

<details>
<summary>File 1</summary>

      
      const { createClient } = require("@supabase/supabase-js");
      
      const supabase = createClient(
        "https://my-url.supabase.co",
        "my-key",
        {
          realtime: {
            log_level: "info",
            params: {
              eventsPerSecond: 10,
            },
          },
        }
      );
      
      const channel = supabase.channel("online-users", {
        config: {
          presence: {
            key: "user1",
          },
        },
      });
      
      channel.subscribe(async (status) => {
        if (status === "SUBSCRIBED") {
          const status = await channel.track({ online_at: new Date().toISOString() });
          console.log("Status: ", status);
        }
      });
      
      channel.on("presence", { event: "sync" }, () => {
        console.log("Online users: ", channel.presenceState());
      });
</details>

<details>
<summary>File 2 (same as file 1 with different user</summary>

      
      const { createClient } = require("@supabase/supabase-js");
      
      const supabase = createClient(
        "https://my-url.supabase.co",
        "my-key",
        {
          realtime: {
            log_level: "info",
            params: {
              eventsPerSecond: 10,
            },
          },
        }
      );
      
      const channel = supabase.channel("online-users", {
        config: {
          presence: {
            key: "user1",
          },
        },
      });
      
      channel.subscribe(async (status) => {
        if (status === "SUBSCRIBED") {
          const status = await channel.track({ online_at: new Date().toISOString() });
          console.log("Status: ", status);
        }
      });
      
      channel.on("presence", { event: "sync" }, () => {
        console.log("Online users: ", channel.presenceState());
      });
</details>

## Expected behavior

Running both the files shows the online users correctly when any client joins or leaves. Since `log_level: info` is given, as mentioned in [docs](https://supabase.com/docs/guides/platform/logs#logging-realtime-connections) the dashbaord should show the connection event logs.

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: 16.15.1

## Additional context

Using supabase web

**Comment by filipecabaco** [comment]
With the following code:
```ts
const supabase = createClient(url, apikey);
const channel = supabase.channel("test");
channel.subscribe(async (status) => {
  if (status !== "SUBSCRIBED") return;
  await channel.track({ user: "user" });
});
```
And the following query:
```sql
select
  cast(timestamp as datetime) as timestamp,
  event_message, metadata 
from realtime_logs 
where event_message LIKE '%presence_diff%'
limit 10
```
I was able to fetch the joins in the logs:
<img width="1148" alt="Screenshot 2023-11-17 at 19 30 04" src="https://github.com/supabase/realtime/assets/1697301/b4ebb3a0-55fe-4069-8c8a-d4e16316f5af">

Is this the use case you needed?

**Comment by filipecabaco** [comment]
Closing the issue for now, if it's not solved please reopen
