### ISSUE TITLE
BUG:  Error polling replication: %DBConnection.ConnectionError

### ISSUE THREAD

**Issue by nkreiger** [supabase/realtime#575]
# Bug report

- [ x (I think - could be db configuration) ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Realtime engine is dropping the connection against my Cloud SQL Database (GCP). Throwing the following error:

```
16:17:16.385 project=realtime external_id=realtime [error] Error polling replication: %DBConnection.ConnectionError{
  message: "tcp recv: closed",
  severity: :error,
  reason: :error
}
```

followed by subsequent

```
16:17:16.385 project=realtime external_id=realtime [error] Error polling replication: %DBConnection.ConnectionError{
  message: "tcp send: closed",
  severity: :error,
  reason: :error
}
```

## To Reproduce

1. Run Bitnami Supabase Realtime Image in Kubernetes
2. Scale to 2 replicas
3. Create new client and connect..works fine for about a minute
4. Client drops and that error continuously shows up, new connections no longer work

## Expected behavior

Realtime should attempt reconnect to the DB if the client is closed.

I should not have to completly kill the realtime pods for it to clear out the connection and start working again.

## System information

- bitnami/supabase-realtime:2.10.0-debian-11-r0

## Additional context

Running in kubernetes cluster
GCP cluster
Connecting against GCP Cloud Database -- Using a User with Replication Enabled
Works fine until it drops

**Comment by nkreiger** [comment]
UPDATE:

```
16:27:36.496 [error] Postgrex.Protocol (#PID<0.3136.0>) disconnected: ** (DBConnection.ConnectionError) tcp send: closed
16:27:38.564 project=realtime external_id=realtime [info] Stop tenant realtime because of no connected users
16:27:38.564 [warning] PostgresCdcRls terminated: "realtime" realtime@127.0.0.1
```

After about 10 minutes, it does clear itself out, and connections work again...but that's 10 minutes of lost events

**Comment by nkreiger** [comment]
UPDATE:

investigating the cause as running multiple replicas, without setting the DNS_NODES value

**Comment by nkreiger** [comment]
Closing this, as I believe not setting `DNS_NODES` with replicas, was the issue.

**Comment by rbkayz** [comment]
Can you explain how to do this? Facing the same issue of dropped events

**Comment by filipecabaco** [comment]
Usually this error means that Realtime was not able to connect to the database. @rbkayz are you losing events on self host?

**Comment by filipecabaco** [comment]
could you open a ticket so I can have all the information needed to check your logging?

**Comment by rbkayz** [comment]
Thanks a lot @filipecabaco - we're already connected on email. `Project ref: wvtpktbhobaopdiawdli`

**Comment by filipecabaco** [comment]
is it an open issue? if not lets reopen if needed so we can provide more help in case I need to bring other teams to the discussion 👀
