### ISSUE TITLE
Realtime version and release don't match

### ISSUE THREAD

**Issue by fmulero** [supabase/realtime#605]
# Bug report
- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In latest [release](https://github.com/supabase/realtime/compare/v2.14.0...v2.15.0), the tag name and `realtime version` are not aligned. I haven't seen this issue in previous releases.

## To Reproduce

If we build main branch, the result of running `realtime version` is  `realtime 2.14.1` instead of `realtime 2.15.0`.

## Expected behavior

```console
$ realtime version
realtime 2.15.0
```

## Screenshots

N/A

## System information

N/A

## Additional context

N/A

**Comment by chasers** [comment]
Thanks! Fixed!!
