### ISSUE TITLE
Docker hub `latest` image tag is very old

### ISSUE THREAD

**Issue by liamkinne** [supabase/realtime#618]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The `latest` tag is on a much older release on docker hub.

Causes errors using the newest docker-compose since it expects files to exists that don't.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `docker pull supabase/realtime`
2. Using the docker-compose file in the repository.
3. `docker-compose up`
4. Errors due to missing files.

## Expected behavior

The `latest` tag points to the latest (stable?) release so when someone pulls they get the latest release.

## Screenshots

<img width="606" alt="Screenshot 2023-07-12 at 22 44 35" src="https://github.com/supabase/realtime/assets/10735142/4b708f7d-f549-43ab-bc08-171e5d4c960c">

## System information

N/A

**Comment by ventsyv** [comment]
Just spent couple of hours scratching my head why the docker image is not matching the Dockerfile in the repo.

**Comment by ventsyv** [comment]
BTW, the bitnami image seems to be more recent:
```
bitnami/supabase-realtime   latest    70d592e96c09   5 hours ago     115MB
supabase/realtime           latest    b6284e15dee3   12 months ago   195MB
```

**Comment by filipecabaco** [comment]
Changed the CI cycle to properly release the latest version. Thank you for reporting 🙏
