### ISSUE TITLE
Extract out replication functionality

### ISSUE THREAD

**Issue by cpursley** [supabase/realtime#62]
I'd love to use just the replication / data change functionality directly in Elixir so that I can do stuff on the data (no need to publish the data out). Is there any chance this functionality could be extracted out into it's own library? Or can you recommend how I can go about it myself?

**Comment by soedirgo** [comment]
Hi @cpursley! This was discussed here: https://github.com/supabase/realtime/issues/44.

In short, this is meant to be a standalone server. You can use [cainophile](https://github.com/cainophile/cainophile) if you want the CDC functionality as a library (though it doesn't seem to be active, unfortunately).
