### ISSUE TITLE
:unchanged_toast is causing errors

### ISSUE THREAD

**Issue by toder34** [supabase/realtime#64]
Just as a gentle reminder, the `latest` docker image for `supabase/realtime` still has this bug. I tracked it down to this issue and rebuilt from the latest code in the repo using the provided `Dockerfile` and it has resolved.

_Originally posted by @kwakwaversal in https://github.com/supabase/realtime/issues/50#issuecomment-680260503_

**Comment by kiwicopple** [comment]
Thanks for the creating this @toder34 - I renamed this to make it easier to track.

This was fixed here:
https://github.com/supabase/realtime/commit/c1ea779d6b723823ebbb266694a913ff58982b1b#diff-fa0378d0927ab8b4ed0ffb41e22d4b51R65

It should just be a matter of releasing. After releasing we should test again (https://github.com/supabase/realtime/issues/50#issuecomment-642685807).

I suspect the server wasn't built before shipping

**Comment by kiwicopple** [comment]
Github action seems to be skipping the release

**Comment by kiwicopple** [comment]
![image](https://user-images.githubusercontent.com/10214025/92087170-c7093680-edfd-11ea-854b-31fd78cc8d9e.png)

OK this time it looks like `latest` is the same timestamp and size as `v0.7.8`

Let me know if you still have issues with this on the latest image. Thanks for the patience!
