### ISSUE TITLE
> Does supabase have null filters?

### ISSUE THREAD

**Issue by sathishkannan162** [supabase/realtime#661]
> Does supabase have null filters?

@sathishkannan162 realtime doesn't currently support is null filters but it's something we can add to the product roadmap. will transfer this to the realtime repo.

_Originally posted by @w3b6x9 in https://github.com/supabase/realtime/issues/659#issuecomment-1707317519_

**Comment by filipecabaco** [comment]
Will close this issue in favor of #659 since it has more information. We will take into consideration new filters in the next stages of development
