### ISSUE TITLE
Event parser

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#73]
# Feature request

Right now we are blindly sending all events over the websockets. For various reasons (primarily security), a developer may want to filter which events are sent out. In the future this could also extend to include JSON transformer discussed [here](https://github.com/supabase/realtime/issues/66#issue-686574252).

## Describe the solution you'd like

We already have the Configuration manager for adding webhooks:

```ex
    config = [
	%Configuration.Webhook{ 
	  event: "*",
	  relation: "public:todos",
        }
      ]
```

we can probably re-use this for Realtime:

```ex
    config = [
	%Configuration.Realtime{
	  event: "*",
	  relation: "public:todos",
        },
	%Configuration.Realtime{
	  event: "*",
	  relation: "public:users:id",
        },
      ]
```

If this config is present, the realtime server will stop sending events for everything, and only send events matching the rules specified, although I can see cases where people want to allow everything, and then uses these rules to enrich _some_ routes. 

In this case the Realtime server will only send events that happen on the `todos` table (including all the columns? ie: `todos:id.eq.1`), and on the `public:users:id.eq.*` channel.

This is a workaround using security through obscurity. For example, if the user ID is a `uuid`, then it will be fairly difficult to listen to other users' data - `supabase.from('users:id = eq.21a285d7-6028-4967-a2a9-fb5afdc9a4b4').on('*', () => {})`

Finally, in the future we may extend this with a transformer:

```ex
    config = [
	%Configuration.Realtime{
	  event: "*",
	  relation: "public:todos",
          transformer: '.[0] | {message: .commit.message, name: .commit.committer.name}' # fake, using jq filter
        }
      ]
```

## Describe alternatives you've considered

None come to mind, but I'm not particularly happy with this part: 

> I can see cases where people want to allow everything, and then uses these rules to enrich _some_ routes

Also I don't particularly like how the "Channels" config is now mixed in with the "Connectors" config.

## Additional context

- Related: [Configuration Manager](https://github.com/supabase/realtime/issues/48) for handling config
- Related: [JSON parser](https://github.com/supabase/realtime/issues/66) for filtering the payload data

edit: @awalias changed:
`supabase.from('users:id.eq.21a285d7-6028-4967-a2a9-fb5afdc9a4b4').on('*', () => {})` to
`supabase.from('users:id = eq.21a285d7-6028-4967-a2a9-fb5afdc9a4b4').on('*', () => {})`

**Comment by kiwicopple** [comment]
@fracek in case you're available, I'd love your opionion on this one. I think I will need to implement it soon as realtime security is becoming more important for some of our customers

**Comment by fracek** [comment]
What you propose is a reasonable extension to what Supabase already has. I share your concern as well.

> If this config is present, the realtime server will stop sending events for everything, and only send events matching the rules specified, although I can see cases where people want to allow everything, and then uses these rules to enrich some routes.

In my experience this tends to be confusing to users (at least when I'm the user :smiley: ), would it be possible to have a default configuration that sends all events? I see the following advantages:

* Eliminates magic behavior
* Provides a starting point for users to write their own filters
* It's the perfect place to link to the documentation where we describe how the filter works

**Comment by kiwicopple** [comment]
> have a default configuration that sends all events

Good solution. Nice suggestion Fracek
