### ISSUE TITLE
Erroneous public.test_tenant file from Supabase Realtime Migrations

### ISSUE THREAD

**Issue by nbarrow-inspire-labs** [supabase/realtime#745]
This line (https://github.com/supabase/realtime/blame/edbd6a1b013e5bccdd4bbae456aa9d479ec40247/priv/repo/seeds.exs#L50) is causing a table to show up in the `public` schema. I tried hunting down when it was introduced, but was unsuccessful.

CLI Version: 1.112.0

**Comment by nbarrow-inspire-labs** [comment]
<img width="1624" alt="Screenshot 2023-11-18 at 2 39 00 PM" src="https://github.com/supabase/realtime/assets/127700939/d40a5009-8979-4336-aeba-791538c4de55">

**Comment by filipecabaco** [comment]
This has been fixed in the latest CLI version

https://github.com/supabase/cli/issues/1662

Thank you for reporting and sorry for the inconvenience

**Comment by nbarrow-inspire-labs** [comment]
No worries, thanks for catching that! @filipecabaco I'm on 1.112.0 and ran `brew upgrade supabase` first before filing this, but perhaps the brew release hasn't caught up yet.

**Comment by filipecabaco** [comment]
I will ping the CLI team to understand the brew release cycle 👀

**Comment by filipecabaco** [comment]
Ok got some information about it 😄 

https://github.com/supabase/cli/blob/main/CONTRIBUTING.md#release-process

If you use the beta channel you will have access to this latest version
