### ISSUE TITLE
unable to filter delete realtime messages

### ISSUE THREAD

**Issue by SweeToxin** [supabase/realtime#75]
# Bug report

## Describe the bug

Realtime filter doesn't work properly on Delete subscription, it seems to filter all messages. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```js
supabase.from(`${table}:${column}=eq.${value}`)
  .on('DELETE', () => console.log("random text"))
  .subscribe()
```

## Expected behavior

Only messages respecting the condition should go through. 

## Screenshots

n/a

**Comment by awalias** [comment]
thanks @SweeToxin we'll try and reproduce.

@phamhieu since you were testing realtime + dart, did you happen to test deletes today?

**Comment by phamhieu** [comment]
I only tested INSERT. I will check it again later.

**Comment by kiwicopple** [comment]
Hi @SweeToxin ! Nice to see you in our repos too 

Could you please try this?

```js
supabase.from(`${table}:${column}=eq.${value}`)
  .on('DELETE', (change) => console.log('Change:', change))
  .subscribe() // <---- add the subscribe function here
```

**Comment by SweeToxin** [comment]
Thank you @kiwicopple! 
Sorry I might have wrote the example code wrong, I will correct it. 

I am actually using the `.subscribe()` 
The code is working perfectly for INSERT and UPDATE, the issue only shows on DELETE subscription.

**Comment by kiwicopple** [comment]
OK, can you try one more thing @SweeToxin ? Can you run 

`ALTER TABLE your_table REPLICA IDENTITY FULL;`

on whichever table you're listening to?

**Comment by SweeToxin** [comment]
Hey, 
After trying that, it still doesn't work for DELETE ( both insert and update are working fine ). 

This is the actual code if it helps

```js
function startRealTime(table, store, userId) {
  supabase
    .from(`${table}:owner=eq.${userId}`)
    .on('INSERT', onItemChange(store))
    .on('UPDATE', onItemChange(store))
    .on('DELETE', onItemDelete(store))
    .subscribe();
}
```

**Comment by soedirgo** [comment]
I'm able to reproduce this with this setup:

supabase-js:

```html
<!DOCTYPE html>
<html>
  <script type="module">
    import { createClient } from "https://cdn.skypack.dev/@supabase/supabase-js";

    const supabase = createClient("https://[...].supabase.co", "[...]");

    supabase
      .from("users:id=eq.1")
      .on("INSERT", (payload) => {
        console.log("Insert received!", payload);
      })
      .on("UPDATE", (payload) => {
        console.log("Update received!", payload);
      })
      .on("DELETE", (payload) => {
        console.log("Delete received!", payload);
      })
      .subscribe();
  </script>
</html>
```

Supabase:

```sql
CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text
);

insert into users (name) values ('a');
update users set name = 'b' where id = 1;
delete from users where id = 1;
```

Will look into this!

**Comment by SweeToxin** [comment]
Hey @soedirgo, 
Thank you for taking the time to look into this

**Comment by kiwicopple** [comment]
OK found the issue: https://github.com/supabase/realtime/blob/9a39fb264a86cc2b13bd15581d4dc5a335beab96/server/lib/realtime/subscribers_notification.ex#L64

This is mapping through the keys in `record`, however a DELETE change looks like this:

```
{
  "columns": [
    {
      "flags": [
        "key"
      ],
      "name": "id",
      "type": "int4",
      "type_modifier": 4294967295
    },
    {
      "flags": [],
      "name": "test_col",
      "type": "varchar",
      "type_modifier": 4294967295
    }
  ],
  "commit_timestamp": "2020-11-10T08:05:32Z",
  "old_record": {
    "id": "3",
    "test_col": "qwe"
  },
  "record": {},
  "schema": "public",
  "table": "test_table",
  "type": "DELETE"
}
```

There are no keys in `record`, because it's a deletion. For DELETE's, we would need to loop through the `old_record`. 

@soedirgo I wonder if you roll this update into your changes in https://github.com/supabase/realtime/pull/76 ?

**Comment by kiwicopple** [comment]
Thanks for the patience on this one @SweeToxin - I just pushed the fix, and we will bundle it into the next deployment in supabase.
