### ISSUE TITLE
Seeds broken in latest docker image

### ISSUE THREAD

**Issue by menasheh** [supabase/realtime#759]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When running the docker-compose in latest master, the seeds don't run and tenants table cannot be found.

## To Reproduce

1. git clone git@github.com:supabase/realtime.git
2. cd realtime
3. docker-compose build
4. docker-compose up
5. See error in server log

## Expected behavior

Seeds should run correctly

## System information

- OS: Windows

**Comment by filipecabaco** [comment]
@menasheh could you share the errors logged out?

**Comment by menasheh** [comment]
today it worked... not sure what changed
