### ISSUE TITLE
too_many_channels error: `"{:error, :too_many_channels}"`

### ISSUE THREAD

**Issue by barrownicholas** [supabase/realtime#843]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm occasionally getting a `"{:error, :too_many_channels}"` on self-hosted/local. Is there a way to increase the number of channels (env var, etc.)? I saw `MAX_CONNECTIONS` but that doesn't seem right (channels v. connections). 

### Edit 1
It looks like there is `max_channels_per_client`, but I'm not sure/don't see the ability to set this dynamically. I'm not familiar enough with the realtime component to know if this loads dynamically or is set in the db. (It looks like a db row?)

### Edit 2
Okay so the true dev/local using the CLI does **not** use the same as self-hosted/docker `supabase/realtime`... I checked a deployment, and I see below. Is there a way to override the default of `100`?

<img width="1624" alt="Screenshot 2024-04-10 at 10 53 54 PM" src="https://github.com/supabase/realtime/assets/75350582/dc284b3c-de3b-4623-8a8e-a9b21c55678d">

**Comment by barrownicholas** [comment]
Hi All: would it be possible to get a simple `MAX_CLIENTS` variable to override the hard-coded default of 100?

**Comment by barrownicholas** [comment]
I attempted a solution ^

**Comment by filipecabaco** [comment]
this is an issue with CLI environment correct?

**Comment by barrownicholas** [comment]
I get this in our production (self-hosted) environment as well, although theoretically this would exist with the Supabase-hosted too (just given that the default is at 100 with no way of overriding it, aside from the linked PR I submitted).

**Comment by filipecabaco** [comment]
when you use it in self-hosted, do you use the seeded user? would increasing there be enough?

**Comment by barrownicholas** [comment]
@filipecabaco I was trying to brainstorm a solution (like https://github.com/supabase/realtime/pull/866) that would work for both local and self-hosted if that makes sense; I think a CLI solution does definitely fix my localhost CLI issues, it just would leave the self-hosted.

**Comment by filipecabaco** [comment]
sorry for the long silence, tackling other subjects 😓 

for self hosted I think this would also work as at the moment we seed the system with the same file if I'm not mistaken 🤔 cc @w3b6x9

**Comment by barrownicholas** [comment]
@filipecabaco no worries, thanks for getting back to me! @w3b6x9 what are your thoughts on this approach?

**Comment by filipecabaco** [comment]
Really really sorry for the late review, added some comments. If you have any question do ping I will be able to be more responsive this week
