### ISSUE TITLE
Publish arm build for Graviton

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#86]
https://github.com/supabase/infrastructure/issues/343

add arm64 binary download to release page

**Comment by soedirgo** [comment]
Best case scenario is for GitHub to have an ARM runner. The main problem is the need to have the the right ERTS for the target triplet ([ref](https://elixirforum.com/t/how-likely-are-we-to-ever-have-built-in-cross-platform-releases-with-elixir/34559/2)) (unlike Go which can cross compile)
