### ISSUE TITLE
SubscribersNotification process crashes when loading config from json file

### ISSUE THREAD

**Issue by w3b6x9** [supabase/realtime#87]
# Bug report

## Describe the bug

Loading config from a json file:

For example

```
{
  "webhooks": [
    {
      "events": "*",
      "config": {
          "endpoint": "https://webhook.site/93d0c185-5172-4c83-bf36-fa3c4dd02cee"
      }
    }
  ],
  "realtime": []
}
```

crashes the Realtime.SubscribersNotification process.

This is due to PR #76 not converting "realtime" config from json file to :realtime in `Configuration` module.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a config json file in the /server dir with something like:

```
{
  "webhooks": [
    {
      "events": "*",
      "config": {
          "endpoint": "https://webhook.site/93d0c185-5172-4c83-bf36-fa3c4dd02cee"
      }
    }
  ],
  "realtime": []
}
```
2. Run the server with CONFIGURATION_FILE pointing to the config json file
3. Insert row to table

## Expected behavior

Both realtime subscribers and webhook connectors should work as normal.

## System information

- OS: macOS
- Browser: Chrome
- Version of Node.js: 14.11.0

**Comment by soedirgo** [comment]
Closed by #92.
