### ISSUE TITLE
Realtime JS should allow users to unsubscribe from channels with the same name

### ISSUE THREAD

**Issue by kiwicopple** [supabase/realtime#9]
Test:

- Set up 2 listeners on `*`
- Assert that they are receiving changes
- Unsubscribe from one
- Assert the remaining listener is receiving changes

**Comment by dragarcia** [comment]
![image](https://user-images.githubusercontent.com/26374889/80598199-941ff200-8a5b-11ea-98c6-27e88bb5755e.png)
From the [phoenix-js documentation](https://hexdocs.pm/phoenix/js/), we could not actually have more than one channel assigned to a socket that are listening to the same topic. The more recent one will just override the other.

The workaround here is that if you would want to have two channels listening to the same topic, instantiate two sockets, and assign each channel to each socket. Closing one socket will also not affect the other. [supabase/supabase-js](url) operates in such a way at the moment.
